### ISSUE TITLE
关于BiliAccount库的一些使用建议

### ISSUE THREAD

**Issue by LeoChen98** [CHKZL/DDTV#10]
首先十分感谢你引用了我的库，经过阅读了你的代码发现你使用的是二维码登录的方式。

我十分赞同这种不经手账号密码的登录方式，但我也发现你的调用方式存在一些问题：
1. `QrCodeStatus_Changed_Handle`回调函数中应使用`status`判断登录状态，而不是`account`，因为`account`的判定可能出现问题。
>请参考[wiki `BiliAccount.Linq.ByQrCore.QrCodeStatus`部分](https://github.com/LeoChen98/BiliAccount/wiki/BiliAccount.Linq#QrCodeStatus)

2. `account`是提供了字符串类型cookies的，你完全可以不需要自己转换，直接访问`account.strCookies`即可。
>请参考[wiki `BiliAccount.Account`部分](https://github.com/LeoChen98/BiliAccount/wiki/BiliAccount#Account)

3. 我个人不建议你以明文的方式储存登录后的cookies，这可能会带来一定的安全问题，如有必要可以考虑加密保存，如无必要，可以考虑每次启动时让用户扫码登录。

另外，`BiliAccount`库采用MIT授权，希望你能遵守MIT协议，在软件中携带版权信息。如果对`BiliAccount`库有更多需要帮助的问题可以访问[wiki](https://github.com/LeoChen98/BiliAccount/wiki)或[提交issue](https://github.com/LeoChen98/BiliAccount/issues/new)

**Comment by CHKZL** [comment]
感谢您的库和建议。
判断和储存等问题已经在最新的代码里修复
从在2.0.2.0之后在主程序里面就有标注应用的库和插件来源标注，也在最新的更新里说明了一下
