### ISSUE TITLE
room config刷新

### ISSUE THREAD

**Issue by dfmjndm** [CHKZL/DDTV#106]
版本2.0.6.1a
网页上每次修改roomconfig后不会立刻起效开始录制还要去后台重启软件。。。

**Comment by CHKZL** [comment]
不是没有立即生效
是如果加入房间后才打开“自动录制”这个设置会在下一次房间开播状态变化才会工作。。

**Comment by moomiji** [comment]
config真没改变，开启关闭都没工作

- 开启录制

![image](https://user-images.githubusercontent.com/35213527/136662281-aa193506-195b-4664-939e-81896a717148.png)

- 关闭录制

![image](https://user-images.githubusercontent.com/35213527/136662965-3ca55cc3-4dc5-41c7-bf0f-d4a5deacfc74.png)

![image](https://user-images.githubusercontent.com/35213527/136663107-cc752fb6-77d6-40e6-bdb9-1a708af6a393.png)

**Comment by moomiji** [comment]
> 我这边是正常的，而且也可以自动开始录制

草我懂了，就当我看花了眼

但房间开播状态变化后才开始录播，有点反直觉了
