### ISSUE TITLE
度盘上传

### ISSUE THREAD

**Issue by dfmjndm** [CHKZL/DDTV#107]
ddtv.pro里面怎么把百度云上传的那个upload删掉了，我在配置文件把百度云上传开了但是没有作用

**Comment by NagisaCo** [comment]
配置方法可以先参照这里
[https://github.com/NagisaCo/DDTV2/blob/dev-upload/DDTVLiveRec/README.md](https://github.com/NagisaCo/DDTV2/blob/dev-upload/DDTVLiveRec/README.md)

文档的问题之后会修复的
