### ISSUE TITLE
合并出来的文件中间会有一大段的直接跳过的长度,4个小时拉到7个小时是为什么

### ISSUE THREAD

**Issue by SZCDSB** [CHKZL/DDTV#110]

**Comment by CHKZL** [comment]
那应该是录制或者合并的时候自动时间轴修复错误了，实际上视频内容都存在，可以尝试用修复工具或者直接用FFmpeg进行-c 封装一下即可，也可以加一下官网里`关于项目`中的群方里便沟通解决
