### ISSUE TITLE
有考虑过增加软解功能吗

### ISSUE THREAD

**Issue by vcfee** [CHKZL/DDTV#111]
我的5600x配760显卡，开3个直播间，cpu占用只有7%左右但是GPU已经100%了，再多开软件就崩溃，而且第三个窗口花屏马赛克严重，对这方面不太了解，能实现cpu解码吗

**Comment by CHKZL** [comment]
我正在推送更新DDTV3.0，你可以尝试一下最新版本的应该能解决这个问题

**Comment by CHKZL** [comment]
3.0中应该没有这个问题了，展示先closed了，如果有问题请再提一下
