### ISSUE TITLE
当关注列表添加一个没有直播间的主播时，会导致DDTV_GUI无法启动

### ISSUE THREAD

**Issue by shadow7755** [CHKZL/DDTV#113]
前几天手动无意添加了一个没有开直播间的主播，重启后发现DDTV_GUI无法启动了，经过反复修改监控列表的json发现，应该是RoomListConfig.json，中如果主播没有开直播间，那么RoomId就是0，这会导致DDTV_GUI无法启动，json里的房间信息如下：
{
		"name": "寝月nero_Official",
		"Description": "",
		"RoomId": 0,
		"UID": 1997210725,
		"IsAutoRec": false,
		"IsRemind": true,
		"IsRecDanmu": false,
		"Like": false
}

**Comment by CHKZL** [comment]
在 #113 中修复了这个问题，自动更新Ver3.0.1.8已经推送
