### ISSUE TITLE
DDTV无法最小化到托盘

### ISSUE THREAD

**Issue by Rikkalxn** [CHKZL/DDTV#114]
更新了最新版的DDTV之后，没法最小化到托盘了。任务栏上的图标一直在那还挺不方便的

**Comment by CHKZL** [comment]
这是因为渲染方式的原因，可能导致部分用户缩小后无法再次打开窗口而，所以做了这次更新，下次更新我会在设置里面添加选项，让用户自己选择缩小方式。

**Comment by CHKZL** [comment]
在最新的版本的设置中增加了选项，可以根据自己的情况开关该功能
