### ISSUE TITLE
同时观看多个直播时，发送弹幕/打开弹幕会卡住

### ISSUE THREAD

**Issue by hulucc** [CHKZL/DDTV#118]
windows 10，3.0.1.9

**Comment by CHKZL** [comment]
请问能稳定复现么，我本地测试打开多个直播窗口然后发送弹幕没有触发这个问题
如果能稳定复现可以描述一下流程嘛？

**Comment by CHKZL** [comment]
已修复，如果没推送更新，手动运行DDTV_Update即可
