### ISSUE TITLE
查询全局设置时的安全问题

### ISSUE THREAD

**Issue by Polyisoprene** [CHKZL/DDTV#119]
在制作前端全局弹幕录制和自动转码的开关时，要知道起始全局弹幕录制和自动转码是为true还是为false。但是这两个配置项是通过system_config来查询的，返回的结果内包含所有的全局设置，包括用户名和密码，所以感觉不太安全。 
能不能将可以通过api来设置的全局状态的查询单独放在一个api里

**Comment by CHKZL** [comment]
这并没有问题，能请求system_config接口，那么就代表着，两种接口方式至少知道其中一种的验证字符串了，本身就是有权限知道这个值的。

**Comment by CHKZL** [comment]
在 c8aa60e17fff17b18da5b2cf9a18d9c2578dee96 中给System_Config接口增加参数用于隐藏敏感数据
