### ISSUE TITLE
手动取消录制会自动重新开始

### ISSUE THREAD

**Issue by tinyAdapter** [CHKZL/DDTV#12]
版本是最新的2.0.2.1d

如图，每次点击取消下载后都会自动重新开始新的录制，看起来似乎「根据断流原因选择是否自动重连」部分的逻辑出了问题？

![image](https://user-images.githubusercontent.com/8264895/80388737-d1aa4100-88dc-11ea-9ae5-4556d89573b7.png)

**Comment by CHKZL** [comment]
我这段时间重写和新增了一些重要功能，这个问题已经被修复了，这两天就会更新

2.0.2.2a更新预览：

2.0.2.2对比2.0.2.1b更新内容
增加:
DDTVLiveRec项目(需要单独下载)，一个纯粹的自动录制下载工具，支持windows,linux(x64，ARM)，macOS，也就是路由器，树莓派什么的也可以录制啦
断流续下后自动合并Flv文件的功能
录制结束后自动转码为MP4文件并修复时间轴
全新的消息文件系统
【正在写】提供日志和下载文件状态查看功能的网页功能

修改:
从之前的 [只录制启动后开播的视频流] 修改为[动后会马上根据配置列表开始录制]
下载系统更新为2.0
修复设置界面的输入框输入困难的问题
优化稳定性和修复了一箩筐的彩蛋(bug)

**Comment by CHKZL** [comment]
还有一个更重要的问题(((
我仔细观察了一下你发的截图，你这是播放缓冲，双击列表开始观看的直播，也算是一个“下载任务”，这个任务只要播放窗口不关闭，就会永远尝试重连，除非该直播间的直播状态更改。
所以这并不是一个bug。

**Comment by tinyAdapter** [comment]
额，并不是（

我是在单推列表直接选中列然后点的“录制选中房间”，然后就给了我这个一直重连的下载任务

从始至终都没开过直播（

**Comment by CHKZL** [comment]
我这周末会推送2.0.2.2a版本，这个问题已经被解决了，2022a更新功能预览：

Ver2.0.2.2(预计五一发布)

2.0.2.2对比2.0.2.1b更新内容
增加:
DDTVLiveRec项目(需要单独下载)，一个纯粹的自动录制下载工具，支持windows,linux(x64，ARM)，macOS，也就是路由器，树莓派什么的也可以录制啦
断流续下后自动合并Flv文件的功能
录制结束后自动转码为MP4文件并修复时间轴
全新的消息文件系统
【正在写】提供日志和下载文件状态查看功能的网页功能

修改:
从之前的 [只录制启动后开播的视频流] 修改为[动后会马上根据配置列表开始录制]
下载系统更新为2.0
修复设置界面的输入框输入困难的问题
优化稳定性和修复了一箩筐的彩蛋(bug)

**Comment by tinyAdapter** [comment]
OK👌

话说你好能写啊，我都研究不来直播这套的（

**Comment by CHKZL** [comment]
发布的Ver2.0.2.2a中已经修复这个问题

**Comment by tinyAdapter** [comment]
这边测试没修好啊……（虽然备注和上次不一样了）

![image](https://user-images.githubusercontent.com/8264895/80821070-a5f3c780-8c0a-11ea-9c5f-21238303fd0c.png)

**Comment by CHKZL** [comment]
emmmm，能详细描述一下过程吗
我这边看能不能复现一下....

**Comment by tinyAdapter** [comment]
单推列表里随便点个直播间，点击“录制选中房间”，等“下载任务添加完成”对话框出现后，点击”查看下载队列“，选中第1行，点击“取消下载”，点击”OK“，然后就会出现第2行备注”重连“的任务

**Comment by CHKZL** [comment]
我换着姿势重新测试了几次都没重现出来....

**Comment by CHKZL** [comment]
![GIF 2020-5-2 19-58-48](https://user-images.githubusercontent.com/20613600/80863539-b316c200-8caf-11ea-8de7-f7efa260142d.gif)
是这样操作么？

**Comment by tinyAdapter** [comment]
刚才试了一下重新下载最新的完整版，还是跟下面一样的结果……

![2020-05-02-20 04 17 193](https://user-images.githubusercontent.com/8264895/80863627-418b4380-8cb0-11ea-995c-59b2464563a0.gif)

**Comment by CHKZL** [comment]
我仔细研究了一下可能触发这个效果的逻辑，我找到了一个会触发这个情况的问题....你的系统设置语言不是简体中文吧.....

**Comment by tinyAdapter** [comment]
emmm没错

**Comment by CHKZL** [comment]
我之后会修复这个问题，更新到DDTV群共享，因为暂时没有收到其他这个bug的报告，就不推送全体更新了，麻烦加群307156949在群共享下载一下((((
