### ISSUE TITLE
希望加入webhook的功能

### ISSUE THREAD

**Issue by KNaiFen** [CHKZL/DDTV#122]

**Comment by CHKZL** [comment]
这个功能之前在DDTV2.x上有实现，现在3.x重构后还未增加这个功能，我准备在马上的3.0.2.2版本中增加上webhook

但是不太清楚一般这个功能需要在哪些事件后触发和具体的使用情况是怎样的

能不能麻烦加群338182356，好好讨论一波(

**Comment by KNaiFen** [comment]
关于有啥要触发的，我感觉可以参考一下BLREC的这方面，不过DDTV的功能远不止录播，还有很多别的方面也用得到WEBHOOK，我也只了解录播的方面。。。

**Comment by CHKZL** [comment]
在最新的3.0.2.2版本中已经实装了这项功能，详情可以查看[DDTV官网上进阶功能说明中的WebHook说明文档](https://ddtv.pro/AdvancedFeatures/Webhook.html)
