### ISSUE TITLE
闪退问题，输入的监控up主id如果是错误会发生闪退。

### ISSUE THREAD

**Issue by WayneCrow** [CHKZL/DDTV#127]
使用时因为没有注意输入的是up主id号，输入成房间号了。然后输入后就会自动闪退
如果可以建议输入后可以给个弹窗，提示监控的up主”ID名“是什么。然后选择是否监控该up主。如果ID是错误的则提示“无法查到此ID，请确认该ID号是否正确”
最后感谢提供这个软件，支持一下

**Comment by CHKZL** [comment]
请问你用的是哪个版本？我应该在之前的某个版本中修复了这个问题才对（大概是3.0.2.3）

**Comment by WayneCrow** [comment]
Core-3.0.2.5
也可能是因为我用m1的mac虚拟机运行的，所以出现些bug

**Comment by CHKZL** [comment]
才推送了3.0.2.6，推送前我测试过没问题了，更新一下试试，这个我先close了，如果还有提个新的issues
