### ISSUE TITLE
电脑如果非正常关机时可能导致ddtv重新初始化

### ISSUE THREAD

**Issue by SZCDSB** [CHKZL/DDTV#129]
在长按电源键关机的情况下有较高概率遇到ddtv打开会重新初始化

**Comment by CHKZL** [comment]
DDTV在运行中会以一分钟一次的频率保存配置文件，并不是退出时保存
你说的这种情况应该是是启动后短时间内关机才能触发，正常使用中非正常关机并不会导致会重新初始化
