### ISSUE TITLE
2.0.2.2出现的问题

### ISSUE THREAD

**Issue by uruharushia** [CHKZL/DDTV#13]
覆盖安装之后会把之前添加的名单全给删除，且若没登录pilipili每次登录时就会提示登录信息已过期或丢失，我寻思上个版本不登录都不会这样的，而且在添加V时如果按到取消会导致BUG，页面会变成执行操作中无法关闭，导入列表会显示导入0个，是我win7的问题吗
![6YJ(HKJFMIZ17ZGZ(6 5 KX](https://user-images.githubusercontent.com/64689710/80863752-fa518280-8cb0-11ea-91cf-9d1c671efa2f.png)
![A{A_@FOVLDMP0ZJOLI}`E5O](https://user-images.githubusercontent.com/64689710/80863756-fd4c7300-8cb0-11ea-9967-08a93ba71154.png)
![6Z @~80GK~V6OLS)GJE`)UK](https://user-images.githubusercontent.com/64689710/80863767-09383500-8cb1-11ea-962d-be98ac2e7469.png)

![$YN5PXGRID`AV{{B`$YL`CG](https://user-images.githubusercontent.com/64689710/80863878-c3c83780-8cb1-11ea-99d9-cbf38265be92.png)

**Comment by ntlf9t** [comment]
我也是，原来列表没备份都没了，网络导入也是获取不了

**Comment by CHKZL** [comment]
因为有了一键导入，这个手动添加功能一直没怎么注意
网络导入如果有问题，按照以下步骤试一下
1.下载最新版本的补丁覆盖一下(有更新，但是版本号没变化)
2.启动后登录，然后等待三十秒点击一键导入
3.显示导入成功后等待20秒重启DDTV
应该可以解决

这个问题我现在正在修复

**Comment by CHKZL** [comment]
还有就是确定一下软件目录下的roomlistconfig.json文件里是否有之前的列表

**Comment by CHKZL** [comment]
紧急更新推送了Ver2.0.2.2b
在里面修复了这个恶性BUG
可以直接[点击这里](https://github.com/CHKZL/DDTV2/releases/latest)从GITHUB上下载
或者在307156949群共享中下载

**Comment by uruharushia** [comment]
> 紧急更新推送了Ver2.0.2.2b 
> 在里面修复了这个恶性BUG 
> 可以直接[点击这里](https://github.com/CHKZL/DDTV2/releases/latest)从GITHUB上下载
> 或者在307156949群共享中下载

好的，后续有BUG的话会来提交的，不知道有没有人提过之前那个版本的一个小问题，也可能是仅win7会这样吧。就是因为我经常熬夜挂后台听vtb然后打游戏，vtb结束直播，直播间断开之后因为在打游戏没及时关闭窗口，等打完出来关窗口的时候就会整个DDTV崩溃，不知道这个问题有没有人反馈过

**Comment by CHKZL** [comment]
直播结束后很久都不关掉直播窗口么？我挂一晚上测试一下

**Comment by uruharushia** [comment]
> 直播结束后很久都不关掉直播窗口么？我挂一晚上测试一下

不是关不掉窗口，挂机时间过长然后点关闭播放窗口的那个X时会整个程序崩溃

**Comment by CHKZL** [comment]
触发概率是怎样的？或者是有什么100%可以复现的方法么？

**Comment by uruharushia** [comment]
> 触发概率是怎样的？或者是有什么100%可以复现的方法么？

不太清楚，我刚刚又试了试，好像是真的挂时间太长就会崩溃，这个是我看阿夸B限时候没关掉的窗口，阿夸大概是10点多下播的，我是12点多些去点的关闭窗口，就出现这种情况了
![7YJEXA6D3{4BC$8 U(~3G_R](https://user-images.githubusercontent.com/64689710/80990434-ebadcb80-8e68-11ea-9382-13ebb66be2d0.png)

**Comment by CHKZL** [comment]
挂了三轮12个小时，都没有触发。。。这个issues就挂在这里希望有碰见或者知道的人能说一下复现这个bug的过程..

**Comment by ntlf9t** [comment]
![1](https://user-images.githubusercontent.com/31321865/81406093-88bf7b80-916b-11ea-8c89-7ad30a315234.jpg)
下了最新版本好像导入依旧为0

**Comment by CHKZL** [comment]
> ![1](https://user-images.githubusercontent.com/31321865/81406093-88bf7b80-916b-11ea-8c89-7ad30a315234.jpg)
> 下了最新版本好像导入依旧为0

其他问题可以另外开一个issus
你可以尝试重启DDTV登录后等待一分钟(等待缓存完成)然后导入，多试几次这个步骤。
如果还是不行，可以加DDTV的群下载专门针对这个问题的特殊补丁

**Comment by CHKZL** [comment]
如果有触发崩溃的方法，请另外新开一个issue告知
