### ISSUE TITLE
在DDTV GUI观看直播间，断网后右键关闭本窗口会未响应 | 以及GUI观看时tmp里的flv会不断增大，观看时间过长时小盘用户的硬盘会被写满

### ISSUE THREAD

**Issue by moomiji** [CHKZL/DDTV#131]
触发过程看群文件: 20220424_205110.mp4

**Comment by CHKZL** [comment]
未响应相关的问题已经修复了，缓存文件是必不可少的，这点只能要求至少硬盘剩余空间大于观看一场直播的剩余容量....

**Comment by moomiji** [comment]
太惨了，我现在每晚DD还是会触发硬盘空间不足的通知……

**Comment by CHKZL** [comment]
如果你连看一场直播的剩余空间都没有。。。这已经不是用什么软件的问题了吧= =
