### ISSUE TITLE
合并Docker版的请求

### ISSUE THREAD

**Issue by moomiji** [CHKZL/DDTV#132]
仓库：https://github.com/moomiji/docker-ddtv

将会添加：
- [Doc/docs/install/Docker.md](https://github.com/moomiji/docker-ddtv/blob/master/Doc/docs/install/Docker.md)
- [Docker/](https://github.com/moomiji/docker-ddtv/tree/master/Docker)
- ~~[docker-compose.WEB.yml](https://github.com/moomiji/docker-ddtv/blob/master/docker-compose.WEB.yml)~~
- [docker-compose.yml](https://github.com/moomiji/docker-ddtv/blob/master/docker-compose.yml)
- [docker-ddtv.env](https://github.com/moomiji/docker-ddtv/blob/master/docker-ddtv.env)
- [.github/workflows/Docker_Build_Push.yml](https://github.com/moomiji/docker-ddtv/blob/master/.github/workflows/Docker_Build_Push.yml)
- [.github/workflows/Docker_Release.yml](https://github.com/moomiji/docker-ddtv/blob/master/.github/workflows/Docker_Release.yml)

镜像名称为：
- ghcr.io/chkzl/ddtv/cli
- ghcr.io/chkzl/ddtv/webserver
- ghcr.io/chkzl/ddtv/deps

镜像标签为：
- `latest`
- `debian` `3.0` `3.0.*.*`
- `alpine` `3.0-alpine` `3.0.*.*-alpine`

目前我觉得需要协商的是：
- [x] 合并后的目录结构
- [x] 镜像的名称及标签是否需要修改
- [x] 是否要将 DDTV 镜像上传至 Docker Hub Container Image Library 中
- [x] 是否要去除 libgdiplus 依赖项的安装

需要解决的是：
- [x] #130

**Comment by CHKZL** [comment]
这个什么时候合？
