### ISSUE TITLE
希望增加一个开关，控制是否启用磁盘剩余空间检测

### ISSUE THREAD

**Issue by KafuuKion** [CHKZL/DDTV#141]
在Ver3.0.2.11（Windows GUI）中新引入的磁盘剩余空间检测似乎会每隔一段时间自动执行，而我使用的是一块剩余空间400GB（总容量12TB）的硬盘，所以有充足的空间用来录制。

希望在后续版本中加入开关或选项以控制通知的触发，如：

- 彻底关闭这项通知
- 启用这项通知，且在磁盘空间：
  - 低于指定百分比时通知
  - 低于指定实际容量时通知

非常感谢开发者的辛勤付出，用DDTV的时候我D得很开心（）

**Comment by CHKZL** [comment]
OK，预计今天晚上补全这个功能，然后跑一天测试过后自动推送更新
ps：当前是定死的硬盘剩余容量低于5%就警告，看来这并不科学，目前先提供该功能的开关设置。之后提供自定义百分比的功能

**Comment by KafuuKion** [comment]
非常感谢！

**Comment by CHKZL** [comment]
![image](https://user-images.githubusercontent.com/20613600/177197981-34c80705-6cad-41e4-b2a1-1a2c4d1fc508.png)


已经在 18ac08fcea62531186cda487d5894bccf533034c 中修复
预计明天下午推送

**Comment by CHKZL** [comment]
@KafuuKion 已经推送更新，未进行版本号变更，如需使用该功能，手动点击关于界面中的“更新”即可
