### ISSUE TITLE
疑似多余COM引用

### ISSUE THREAD

**Issue by Akarinnnnn** [CHKZL/DDTV#144]
https://github.com/CHKZL/DDTV/blob/66e69d1d8cf016bd7a067b20fe56fd779c4b578b/DDTV_GUI/DDTV_GUI.csproj#L51-L56
`215d64d2-031c-33c7-96e3-61794cd1ee61`是System.Windows.Forms的GUID，但项目已经启用WinForms。

**Comment by CHKZL** [comment]
在最新的提交内容中已经删除了这个无效COM引用
