### ISSUE TITLE
DDTV_CLI运行后提示GetRequest请求超时或错误

### ISSUE THREAD

**Issue by soulmatelh** [CHKZL/DDTV#145]
![( OCJ2UPHN1EQX1)@`GO_@J](https://user-images.githubusercontent.com/56060453/186388116-49ab5412-dc10-47e5-8352-ad448921c7fc.png)

**Comment by CHKZL** [comment]
这是可控的，只要不是频繁出现（比如一两分钟一次）就是正常的，可以忽视

**Comment by soulmatelh** [comment]
好的
