### ISSUE TITLE
希望加入只播放音频功能

### ISSUE THREAD

**Issue by SZCDSB** [CHKZL/DDTV#148]
黑听人想省点电脑资源

**Comment by CHKZL** [comment]
加入需求池，放假了周末研究研究，增加“只听”功能

**Comment by CHKZL** [comment]
> 黑听人想省点电脑资源

该功能已经推送至Dev渠道，可以使用了，下次版本更新的时候会推送到正式版本中，如果现在就想使用请使用Dev渠道

ps：使用Dev渠道的方式：在设置中打开“接收开发版本更新”后点击右边的更新按钮即可
