### ISSUE TITLE
Windows Server 2022在关闭防火墙、添加白名单的情况下无法获取推流内容

### ISSUE THREAD

**Issue by unknown10777** [CHKZL/DDTV#149]
如题，环境为Windows Server 2022，配有两张virtIO网卡和一张zerotier网卡，其中只有一张virtIO可访问互联网。

**Comment by CHKZL** [comment]
能麻烦加一下Q群：338182356
提供一下LOG文件夹里面对应的日志内容方便排查问题么？

**Comment by CHKZL** [comment]
现在碰到了类似的问题，排查过后发现是因为拥有IPv6地址，但是服务器不可达造成的。关闭IPv6即可。

另外这个issues太久了，先上面的流程试一试吧，如果不行再开心的issues
