### ISSUE TITLE
功能需求：录制中的节目状态里能显示录制中

### ISSUE THREAD

**Issue by ntlf9t** [CHKZL/DDTV#15]
功能需求：录制中的节目状态里能显示录制中。
上次才DDTV问了说是已经有这个功能，今天下了DDTV2最新版本好像依然不会显示录制中。
![2](https://user-images.githubusercontent.com/31321865/81406255-d2a86180-916b-11ea-9db3-5f9365e99f07.jpg)
比如图中1-2是录制的，查看有缓存文件，但是显示是 直播中。
3因为DDTV开的比直播晚，查看并没有自动录播没有缓存文件。
所以希望增加在状态栏里 录制中 提示。
另外DDTV开的比直播晚，录制状态已经打钩一般不会自动录播，希望修复

**Comment by CHKZL** [comment]
这个功能已经在最新版本中应该已经解决了
解决的方法：现在DDTV在启动的时候应该会自动开始录制直播中的房间，不管该房间是否比DDTV开的早。你可以试一试
只要配置文件里录制设置为true，那么只要是开播状态，就会自动开始录像

**Comment by CHKZL** [comment]
如果主要是使用录制功能，更推荐DDTVLiveRec，纯粹的录制工具，配置文件和DDTV共用。

**Comment by ntlf9t** [comment]
好的，我挂几天看看有问题再提
