### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by ghost** [CHKZL/DDTV#152]
win7 DDTV_GUI最新版点击扫码登录后停止运行
![QQ截图20221110111712](https://user-images.githubusercontent.com/117852276/200992847-5d693baa-d6f5-4e38-807c-11e3655bc5ba.png)

**Comment by CHKZL** [comment]
停止运行的的提示窗口有错误详情么？如果方便能加一下 https://ddtv.pro/about/ 上面写的交流群方便沟通么？

**Comment by CHKZL** [comment]
已解决。
原因：进过排查发现是初始化时生成二维码所用到的系统库在WIN7 SP1 旗舰版上还不存在，因为该系统版本不在.NET6的支持列表上。
治标解决办法：使用CLI或者WEB_S版本在终端中进行扫码，生成的配置文件是可以和GUI版本通用的。
治本解决办法：升级到WIN10 19xx 或者更高版本系统
