### ISSUE TITLE
需求：直播完成后更改视频文件标题为下播时标题

### ISSUE THREAD

**Issue by tixwho** [CHKZL/DDTV#156]
当前：视频文件等相关文件名为主播**开播时**标题，但部分主播习惯开播后手动更改标题，导致录制文件标题永远滞后一场直播。
需求：添加能够在主播下播后根据**下播时**标题重命名文件的选项

**Comment by CHKZL** [comment]
在 4f152ae0e8f79ad1b639ca309a65e74131f3f7c0 中已经增加支持，现在已经推送到Dev版本，更新到最新的Dev版本就可以使用了，你可以试试看是否符合你说的需求，确定没问题了再close。  
  
`DDTV_Core.SystemAssembly.DownloadModule.Download.RealTimeTitleFileName`，该功能默认打开，如有特殊需求需要关闭，把Config文件中的`RealTimeTitleFileName`值设置为`False`即可。

**Comment by tixwho** [comment]
只改了mp4文件没有改弹幕之类的其他文件（
要不还是统一一下？

**Comment by CHKZL** [comment]
> 只改了mp4文件没有改弹幕之类的其他文件（ 要不还是统一一下？

在 ac03a88fc9ef8486879bd0e17c556996cea10f57 增加了对其他文件的文件名格式统一，在最新的Dev中也已经推送

**Comment by tixwho** [comment]
ok，都merge了就关了，辛苦了~
