### ISSUE TITLE
重构后sln有三个不存在的项目

### ISSUE THREAD

**Issue by Akarinnnnn** [CHKZL/DDTV#157]
生成日志

MSBuild version 17.4.0+18d5aef85 for .NET
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: 未找到项目文件“D:\src_cloned\DDTV\DDTV_Server\ **DDTV_Server.csproj**”。 [D:\src_cloned\DDTV\DDTV.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: 未找到项目文件“D:\src_cloned\DDTV\DDTV_Update\ **DDTV_Update.csproj**”。 [D:\src_cloned\DDTV\DDTV.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: 未找到项目文件“D:\src_cloned\DDTV\DDTV_Push\ **DDTV_Push.csproj**”。 [D:\src_cloned\DDTV\DDTV.sln]

生成失败。

C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: 未找到项目文件“D:\src_cloned\DDTV\DDTV_Server\DDTV_Server.csproj”。 [D:\src_cloned\DDTV\DDTV.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: 未找到项目文件“D:\src_cloned\DDTV\DDTV_Update\DDTV_Update.csproj”。 [D:\src_cloned\DDTV\DDTV.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(396,5): error MSB3202: 未找到项目文件“D:\src_cloned\DDTV\DDTV_Push\DDTV_Push.csproj”。 [D:\src_cloned\DDTV\DDTV.sln]
    0 个警告
    3 个错误
已用时间 00:00:00.44

**Comment by CHKZL** [comment]
DDTV里面的每个项目在编译的时候请单独针对每个项目生成，不要针对整个方案进行生成或者编译



这并不是不存在项目，因为这几个项目里面有比较敏感的信息（比如推送更新，服务端之类的）。
Server是DDTV的服务端，数据的一致性和更新等内容都是通过Server获取的。
Update是DDTV自动更新程序。
Push是我写的更新推送程序。
Danmu倒是可以删掉，这个是针对部分主播单独写的弹幕显示插件，Danmu这个项目我在后续的更新中卸载即可。
