### ISSUE TITLE
DDTV_GUI 监控列表 建议

### ISSUE THREAD

**Issue by pjy612** [CHKZL/DDTV#159]
1.状态 文字 加个 颜色区分 开播没开播  蓝色 红色 什么的？ 或者 整行加个淡背景色？
2.加个文本框筛选 模糊筛选 房间号 ，昵称，标题 什么的 包含关键词就列出来？

**Comment by CHKZL** [comment]
后续计划做一个新的列表把现在的监控表格把现在的换了，这个事情已经提上日程了，只是平时上班没时间摸鱼进度缓慢，后续有新进展了我在这个issues里面回复

**Comment by CHKZL** [comment]
实际上我这已经做过很多套可能符合需求的设计了，但是都是因为性能和优化的问题放弃了= =
比如下面这些已经出demo的样式：
![image](https://user-images.githubusercontent.com/20613600/216771292-22f61f4e-2312-405c-859e-1da82bdfe87e.png)
![image](https://user-images.githubusercontent.com/20613600/216771392-fa2204f6-2ed7-451d-9d36-6fe425a775a1.png)

----------
然后这是现实（
![C4$1UQ@JC953EM2(2 H)E2F](https://user-images.githubusercontent.com/20613600/216771421-6d58eb7d-2ea4-4515-b2f3-e8efd0ca3f00.png)
![image](https://user-images.githubusercontent.com/20613600/216771412-9ea4c429-799f-4600-9771-84fce4664318.png)

**Comment by pjy612** [comment]
Σ(っ °Д °;)っ 厉害了...
倒是没想多好看。。。其实就是想 能手动调下排序优先级 和 能筛选。。。
不过 前端苦手 ...

**Comment by CHKZL** [comment]
在不能操作表格的情况下，能不能描述一下你对于排序和筛选的需求= =？
我看看能不能在不动这个展示的表格的情况下另外用控件作为补充实现

**Comment by pjy612** [comment]
> 在不能操作表格的情况下，能不能描述一下你对于排序和筛选的需求= =？ 我看看能不能在不动这个展示的表格的情况下另外用控件作为补充实现

因为 我是拿DDTV来看的。不弄录播什么的可能不是主流用户。。。

主要需求其实是想能对列表中的主播进行筛选和排序。

目前其实主观上看不太出排序规则，所以就挺迷的。

目测能看出来的是 开播在上面 然后 摸了在下面。然后 摸了中有开播提醒的 会在 摸了“分组” 顶置。
但是 开播提醒 的 又不会在 直播中“分组” 顶置...

其实 就是看能否在哪儿设置一些主播的排序优先级，或者统一比如 开播提醒的 就会根据状态顶置 或者 额外弄个什么顶置设置。

然后就是 那个监控列表也不能筛选。要是能Ctrl+F模糊搜也行 23333
希望要是能加个 房间号 或者 主播名 什么的模糊查询 也行。。。
不加多的控件的话 看看是不是能只弄个 文本框模糊字符串查询， roomid ，uid ，uname啊 全当 or 条件 只要包含文本框的关键词 就显示在列表里。 
文本框不写就显示全部
至少 这样好找人，毕竟默认300多个，有时候加了人都不知道会出现在哪儿。。。不过 摸了分组好像是根据 名称排序的。

另外就是 目前都是黑字嘛 。所以 摸了 和 直播中 这两状态在 列表中 没有明显的界限  不加开播提醒的话。
没筛选的情况下找人 有点费眼睛。。。

**Comment by CHKZL** [comment]
现在其实是有排序规则的，分为三级权重
一级权重：开播>未开播
二级权重：勾选了录制的>未勾选录制的
三级权重：头字母排序(其中 汉字>字母>日语)

其实理解这个排序后就很容易理解和定位到对应的主播了

另外你提到的搜索功能我倒是有苗头了，可以用取巧的方法实现，功能实现后我会优先推送到开发分支，你可以加Q群：338182356，直接在群里收到最新的更新提示和直接和我对线(

**Comment by CHKZL** [comment]
已经在 c0d913c2e766598383292de869fb323cea92d241 中给GUI的房间监控列表增加了Ctrl+F的搜索功能（提供房间号、UID、昵称模糊搜索三种模式）。

当前已推送到Dev分支，你可以在Dev版本中试试，如果你不知道如何切到Dev或有其他疑问，请加Q群338182356直接和我快乐(
