### ISSUE TITLE
功能建议：建议吧缓存目录文件名称由频道号改成中文名称或者官方名称

### ISSUE THREAD

**Issue by ntlf9t** [CHKZL/DDTV#16]
功能建议：建议吧缓存目录文件名称由频道号改成中文名称或者官方名称
我D那么多翻对频道号找录播文件好累

**Comment by CHKZL** [comment]
在当前的最新版本中[2.0.2.2b]，这个功能已经完成，默认文件夹名称是由"平台_名称_直播间号"组成
![C 1H{4}X}5}3 N`ZPZ7O~V](https://user-images.githubusercontent.com/20613600/81413666-641dd080-9178-11ea-9d6f-d8765894e646.png)

**Comment by ntlf9t** [comment]
重新下了确实已经改变
