### ISSUE TITLE
希望支持开始录制时同时保存直播封面的功能

### ISSUE THREAD

**Issue by HunDunDM** [CHKZL/DDTV#164]
希望能在开始录制的同时保存当前的直播间封面图片，会有助于投录播视频~

（才发现这样一个 DD 录播一体机，太强了！）

**Comment by CHKZL** [comment]
对于直播封面可能保存录制结束的时候的封面更为合理吧？感觉有挺多主播开播后才去改标题和封面（只是我感觉，没统计过）

**Comment by CHKZL** [comment]
在 2b464c0a7210d32316d9b20eadd6a25f48c9337f 中增加了这个功能，详细描述如下：

增加保存录制结束时直播间封面的功能和对应的配置参数“IsSaveCover”（把IsSaveCover打开后冷启动，在录制完成后会在同路径保存直播间封面图一张）

当前已推送到Dev分支，你可以在Dev版本中试试，如果你不知道如何切到Dev或有其他疑问，请加Q群338182356直接和我对线(

**Comment by CHKZL** [comment]
线上版本已经支持该功能，请根据上面的描述启动功能即可，这个issues先close了，有问题再联系吧~
