### ISSUE TITLE
加强保护配置文件的请求

### ISSUE THREAD

**Issue by SyuueenN** [CHKZL/DDTV#167]
我的 DDTV GUI 是在不关机的 PC 上运行的，即几乎只有故障和停电时的**意外关机**。这是前提。

这种情况下重新开机 DDTV 自启动时，**每次都会面临二维码登录和录播路径重置**，频繁地、被自启动程序埋在后面或者忙起来的时候就会忘记重新配置。存错位置事小，但存进没空间的分区或没有登录导致错过录播事大。这样自启动几乎失去了意义。

所以**烦请加强对配置文件的保护**，比如产生更改就备份一次、发现损坏就回档之类的操作。这似乎也是同类软件「B站录播姬」的操作，但这边更好用所以希望能在这种基本的功能点也不要落人下风。

**Comment by CHKZL** [comment]
我这本地针对这个问题专门做过一次修复，我本地测试没触发，你描述的这个是每次断电启动都会出现问题么，没有能具体复现这个问题的步骤？

最好是能提供一下，【启动后提示重新登陆】的那一次和前一次的日志文件是最好


2小时后补充：我刚才在本地尝试了【运行中直接结束进程】【运行中直接关机】【运行中直接断电】都没有复现这个问题。。。果然还是需要具体的复现步骤才行

**Comment by CHKZL** [comment]
再次尝试没有复现= =如果看见了麻烦提供一下复现流程，方便我修复...谢谢

**Comment by SyuueenN** [comment]
> 再次尝试没有复现= =如果看见了麻烦提供一下复现流程，方便我修复...谢谢

抱歉回复迟了，我个人也是只能在断电后看到，没法找到一个复现流程。最近一次断电重启后我看到的是`RoomListConfig.json`和`DDTV_Config.ini`的修改日期更新了，且后者的内容全都变成默认值，这里有这次启动时的日志文件，也许能提供帮助。
[DDTVCoreLog_2023-05-28T10-44-39-21680.zip](https://github.com/CHKZL/DDTV/files/11583553/DDTVCoreLog_2023-05-28T10-44-39-21680.zip)

**Comment by SyuueenN** [comment]
![image](https://github.com/CHKZL/DDTV/assets/42110156/71a862f7-75db-4b51-b747-622e1b001eb3)
断电前的日志文件看了一下最后是这些条目，似乎没什么用。

**Comment by CHKZL** [comment]
目前在多个测试实例和用户报告中应该没有再发生这个问题了，因为这个issues太久了，就像close了，如果有问题请麻烦再开一个
