### ISSUE TITLE
关于FLV文件转码为MP4文件时的文件命名问题

### ISSUE THREAD

**Issue by AsunaKazuto** [CHKZL/DDTV#172]
在FLV文件自动转码为MP4文件时，MP4文件的文件名中的{DATE}和{TIME}为录制完成的日期和时间。

**Comment by CHKZL** [comment]
在最新的Dev版本中已经修复了这个问题，可以直接更新到Dev版本体验，该功能会在下次正式版版本更新的时候一起附带推送

**Comment by CHKZL** [comment]
在最新的版本中已经解决这个问题，先把这个close了，如果还有疑问另外新开一个
