### ISSUE TITLE
采用HLS录制时，部分房间直播已结束，直播录制却一直不结束的问题。

### ISSUE THREAD

**Issue by AsunaKazuto** [CHKZL/DDTV#173]
采用HLS录制时，部分房间会出现直播已结束，直播录制却一直不会结束的问题，且无法手动取消录制。

**Comment by AsunaKazuto** [comment]
直播日期：2023.07.05
直播房间：1370893
[日志下载](https://drive.noire.cc/s/ad2Du3?password=jlb8ue&path=%2F)

**Comment by CHKZL** [comment]
进过排查，怀疑这是由于在线观看\播放模式的FLV模式和录制的HLS模式冲突造成了（因为最近有一些直播间没有FLV流，所以卡住了这个房间的一些关键流程）。
我刚才推送了一个新的Dev更新，在这个新版本中，对在线观看\播放模式添加了对HLS的支持，并且设置为默认使用HLS，应该对于这个问题有比较好的优化，你可以尝试一下，有任何反馈请回复我。

github我不是太经常看，如果有问题最好是加群(338182356 )直接找我比较快。

**Comment by CHKZL** [comment]
在最新的版本中已经解决这个问题，先把这个close了，如果还有疑问另外新开一个
