### ISSUE TITLE
有时候无法正常捕捉弹幕

### ISSUE THREAD

**Issue by xnylym** [CHKZL/DDTV#176]
弹幕文件里有时候是空的，sc啥的也没有办法捕捉，但是直播录制是正常的

**Comment by CHKZL** [comment]
现在的逻辑思维录制完成后，最后一次性全部写入弹幕文件。
之后会修改为实时异步写入

**Comment by CHKZL** [comment]
在最新的版本中应该修复了这个问题，之前一段时间由于接口的更新导致弹幕连接有可能成功了但是不能收到弹幕信息。
并且在最新版本中，不管是完成还是取消，都会默认保留目前已经录制的内容
