### ISSUE TITLE
直播封面保存问题以及希望文件夹名称支持以直播开始时间命名

### ISSUE THREAD

**Issue by lucifere02** [CHKZL/DDTV#179]
目前我的文件夹名称格式是{yyyy}{MM}{dd}-{HH}{mm}{ss}-{TITLE}，弹幕SC礼物文件在录制结束的时候都正常保存在同一个文件夹里，但是直播封面会根据录制结束的时间新建一个文件夹保存，应该是保存的逻辑不一样，希望能够修改成保存到原有文件夹。

另外就是希望支持文件夹的名称以直播开始时间命名，类似{yyyy}{MM}{dd}-本场直播开始时间（时分秒）-{TITLE}，这样可以保证有且仅有本场直播的内容保存在同一个文件夹中，不会因为中断录制而有多个文件夹，也可以直观的看到每次直播什么时候开始的。
最后，感谢开发大佬，软件很好用！

还有一个bug:我打开了加入开发版本更新并更新之后，之前的设置就全初始化了。

**Comment by CHKZL** [comment]
> 目前我的文件夹名称格式是{yyyy}{MM}{dd}-{HH}{mm}{ss}-{TITLE}，弹幕SC礼物文件在录制结束的时候都正常保存在同一个文件夹里，但是直播封面会根据录制结束的时间新建一个文件夹保存，应该是保存的逻辑不一样，希望能够修改成保存到原有文件夹。
> 
> 另外就是希望支持文件夹的名称以直播开始时间命名，类似{yyyy}{MM}{dd}-本场直播开始时间（时分秒）-{TITLE}，这样可以保证有且仅有本场直播的内容保存在同一个文件夹中，不会因为中断录制而有多个文件夹，也可以直观的看到每次直播什么时候开始的。 最后，感谢开发大佬，软件很好用！
> 
> 还有一个bug:我打开了加入开发版本更新并更新之后，之前的设置就全初始化了。

关于这3个问题：
1、封面被单独保存是一个历史原因造成的BUG，目前推送的最新版本GUI_Dev已修复，更新到最新Dev即可尝试

2、这是由于会有大量的主播存在开播环境不稳定、切换码率、设置开播\参数等很多操作，这些操作在阿B和各种软件的设定中就是“下播了，然后再上播”，这种条件下就会造成大量的水平和文件夹，目前录制设置还是会保持按【直播间\时间\文件】的格式进行保存。

3、我发现在最新的一个Dev版本中存在储存判断失误的情况，这个情况只在之前的那一个Dev版本中存在，目前最新的Dev中已经修复。如果之后再次触发问题，请告诉我一下复现步骤或者那一次启动的Log文件（log文件在DDTV根目录的Log文件夹中，文件名就是那一次DDTV启动的时间）
