### ISSUE TITLE
更新之后一键导入账号关注无法使用

### ISSUE THREAD

**Issue by superybq** [CHKZL/DDTV#18]
![image](https://user-images.githubusercontent.com/20632962/81658648-8ad75200-946b-11ea-81d3-2dd95025e1c1.png)
等了十几分钟之后依然是这样.已经确认https://gitee.com/SYXM/vdb/raw/master/vdbList.txt 能正常打开.
Debug.txt中没有任何新记录

**Comment by CHKZL** [comment]
用的什么版本？

**Comment by superybq** [comment]
今天刚release的版本2.0.2.3a

**Comment by tinyAdapter** [comment]
说到这个我想起来了，我之前在改代码测试的时候因为它每次都要弹那个导入的提示框，我就也想登账号，结果也没成功，搞得我去复制了以前版本正常登录的JSON回来😅

**Comment by CHKZL** [comment]
这个问题在刚刚推送的2.0.2.3b已经修复，原因是码云修改了查看源文件的策略，之前是用码云当作缓存，现在改了服务器，可以正常导入了

**Comment by superybq** [comment]
新版本测试成功导入了.
