### ISSUE TITLE
系统开启代理后软件不能联网

### ISSUE THREAD

**Issue by wangwenx190** [CHKZL/DDTV#181]
软件设置里的使用系统代理选项已经关闭了。系统开启代理后，软件无法联网，正在进行中的录制也马上中断了。

**Comment by CHKZL** [comment]
> 软件设置里的使用系统代理选项已经关闭了。系统开启代理后，软件无法联网，正在进行中的录制也马上中断了。

这因该是符合预期的。如果是全局代理，或者其他会拦截转发的操作，这个开关并不能绕过。根据你所使用的代理需要自行配置转发白名单才行。

**Comment by wangwenx190** [comment]
> > 软件设置里的使用系统代理选项已经关闭了。系统开启代理后，软件无法联网，正在进行中的录制也马上中断了。
> 
> 这因该是符合预期的。如果是全局代理，或者其他会拦截转发的操作，这个开关并不能绕过。根据你所使用的代理需要自行配置转发白名单才行。

感谢回答。那请问我需要绕过哪些域名或者IP，从而才能不影响这个软件的正常运行呢

**Comment by CHKZL** [comment]
> > > 软件设置里的使用系统代理选项已经关闭了。系统开启代理后，软件无法联网，正在进行中的录制也马上中断了。
> > 
> > 
> > 这因该是符合预期的。如果是全局代理，或者其他会拦截转发的操作，这个开关并不能绕过。根据你所使用的代理需要自行配置转发白名单才行。
> 
> 感谢回答。那请问我需要绕过哪些域名或者IP，从而才能不影响这个软件的正常运行呢

一般来说，设置这两个域名即可：*.bilibili.com和  *.bilivideo.com

**Comment by wangwenx190** [comment]
好的，谢谢！
