### ISSUE TITLE
无法获取和保存弹幕

### ISSUE THREAD

**Issue by lucifere02** [CHKZL/DDTV#182]
昨天开始所有录播都获取不到弹幕，保存下来的xml文件没有任何内容，重新下载程序、更新至开发版本、更换账号登录都试了还是不行，希望能尽快修复一下，真的很重要，非常感谢！

**Comment by CHKZL** [comment]
尝试更新到最新版本试试看？我尝试在 71c515ed7ca0b6cdfd21e154baf2471e23cbe2ee 里面进行了临时兼容，已经发布为3.5.7.971，直接在应用内更新到最新版本试试。

另外现在在对DDTV进行重构，全部推翻重写，新版本应该会比现在好很多，现在历史包袱太多了。
