### ISSUE TITLE
无法显示录制档案

### ISSUE THREAD

**Issue by XPRAMT** [CHKZL/DDTV#191]
如图
![螢幕擷取畫面 2024-01-24 211415](https://github.com/CHKZL/DDTV/assets/34093551/a1cc90d9-430f-47d5-822a-d5feefdb2208)
![螢幕擷取畫面 2024-01-24 212027](https://github.com/CHKZL/DDTV/assets/34093551/08e7060e-0e91-415d-8ad6-529e301266b3)

**Comment by CHKZL** [comment]
请问这是录制完成后的状态么？有重新启动DDTV吗？因为完成记录只针对本次启动期间完成的内容，重启后会重置内容

**Comment by XPRAMT** [comment]
> 请问这是录制完成后的状态么？有重新启动DDTV吗？因为完成记录只针对本次启动期间完成的内容，重启后会重置内容

是的 重启后会不见
可以加入启动时读取之前录制内容的功能吗

**Comment by CHKZL** [comment]
> > 请问这是录制完成后的状态么？有重新启动DDTV吗？因为完成记录只针对本次启动期间完成的内容，重启后会重置内容
> 
> 是的 重启后会不见 可以加入启动时读取之前录制内容的功能吗

在DDTV3中目前尽量少的进行非修复性的更新。这个问题不影响主体功能，我打算在后续的重构计划中再实现这个功能（指的是DDTV5：https://github.com/CHKZL/DDTV/tree/DDTV5_DEV  ），后续重构功能完成后我会进行推送更新

**Comment by XPRAMT** [comment]
了解 感谢大佬!
