### ISSUE TITLE
feature: get_file_structure接口在文件夹节点也返回相对路径

### ISSUE THREAD

**Issue by moehuhu** [CHKZL/DDTV#197]
![image](https://github.com/CHKZL/DDTV/assets/26929896/b526563c-43af-41a6-b1b7-3b5a57abb923)
前端建立文件树结构时需要一个唯一id，文件夹路径具有唯一性可以直接返回

**Comment by CHKZL** [comment]
已在 eaebf34d550d2f57d11f83bff2cdbc2f17cec56f 中添加

**Comment by moehuhu** [comment]
√
