### ISSUE TITLE
不能修改房间号……

### ISSUE THREAD

**Issue by ShimotsukiH** [CHKZL/DDTV#2]
![image](https://user-images.githubusercontent.com/33424662/64845335-791f7f80-d63c-11e9-9601-5cae3d8f1202.png)
很容易填错房间号变成空间号……
但是要改只能删了重新做……有点麻烦

**Comment by CHKZL** [comment]
房间号作为主键，暂时不支持修改，如果要修改房间号现在只能删掉从新添加
