### ISSUE TITLE
2.0.2.4A的问题

### ISSUE THREAD

**Issue by uruharushia** [CHKZL/DDTV#20]
从上个版本好像就有的问题
DDTV的主窗口老是显示0人在播，实际上是有在播的且能打开。不知道是不是我开了SSR的缘故，SSR关掉后，重启光猫与路由，再重启电脑有时候也是这样。还有就是阿B的服务器延迟最近都是4000ping往上，怪啊

![6EL5I DV31BB6{CL G5RS(M](https://user-images.githubusercontent.com/64689710/82209808-7948eb00-9940-11ea-8fc2-edf3ad8c4fa0.png)
![NW801_H YMXAD4JTO~ }KC0](https://user-images.githubusercontent.com/64689710/82209850-9087d880-9940-11ea-9ae4-678c16ef39b0.png)

**Comment by CHKZL** [comment]
如果是4000+那就不奇怪了...我写的超时时间是3秒
也就是3000ms...超过3000ms默认是“未直播”
这个情况应该是你那的网络问题造成的，这个我也应该没办法（=_=）

**Comment by uruharushia** [comment]
> 如果是4000+那就不奇怪了...我写的超时时间是3秒
> 也就是3000ms ...超过3000ms重置是“未直播” 
> 这个情况应该是你那的网络问题造成的，这个我也应该没办法（= _ =）

我上传一段视频到网盘里，你康康，我也不知道问题原因在哪里，应该不是我网络原因吧？链接：https://pan.baidu.com/s/13CWRA2_dL4EdMLABnYQ75A 
提取码：ye1u

**Comment by CHKZL** [comment]
https://api.vtbs.moe/v1/living
你试一试看看能不能打开这个页面，如果能打开，需要多久？
DDTV左上角的那个数据源服务器，就是获取“哪些正在开播”如果时0ms，那说明没有连接成功..

**Comment by uruharushia** [comment]
> https://api.vtbs.moe/v1/living
> 你试一试看看能不能打开这个页面，如果能打开，需要多久？
> DDTV左上角的那个数据源服务器，就是获取“哪些正在开播”如果时0ms，那说明没有连接成功..

![M4U$O%`W$JIYR(OP0L0({CP](https://user-images.githubusercontent.com/64689710/82357090-3289ec80-9a37-11ea-802a-1c03bba0c816.png)
是这一串东西吗？  打开的话是秒打开的，不存在延迟

**Comment by CHKZL** [comment]
我现在在写自动升级的模块，之后更新就可以快速推送了，方便调试，预计这两天更新，修改了很多小问题，升级了过后你再试一试

**Comment by CHKZL** [comment]
这个问题基本定位为网络线路连接的问题，问题存在于线路或运营商。

在才推送的2.0.3.1a版本中增加了阿B的接口复用，并且增加了自动更新模块，你可以尝试一下

以及可以检查一下IE选项设置中的 [连接]-[局域网(LAN)设置]-[使用自动配置脚本]或者[代理服务器]这两项是否勾选，这两个勾选或许会影响到代码中网络调用相关的代码。

**Comment by uruharushia** [comment]
2.0.3.1的又把配置给清空了。。。LAN设置那的自动配置脚本和代理服务器都是未勾选状态的

**Comment by uruharushia** [comment]
![G0UYY$2IE$QWL`H5 BLT_@J](https://user-images.githubusercontent.com/64689710/82443456-18eab280-9ad4-11ea-997a-effdc8670d0f.png)
![6WE_KM})5V4R)W{WZB`X7ZK](https://user-images.githubusercontent.com/64689710/82443468-2142ed80-9ad4-11ea-8b11-23033fb2f65e.png)

等了快1个钟还是房间数据后台加载中

**Comment by CHKZL** [comment]
emmm，我现在确认是连接服务器的问题了，你试一下开其他线路的全局代理，然后再启动DDTV试一试，我这里尝试了一下用一些使用人数多质量比较差的公共线路试了一下，确实会连不上服务器导致现在这些问题..

**Comment by uruharushia** [comment]
我挂了香港的全局代理，数据源服务器永远都是连接超时，现在没法从网络添加，一直提示等待30秒

**Comment by uruharushia** [comment]
所有节点都试了，毛子、土澳、本子、湾湾，棒子的节点都用了数据源服务器都是超时状态，现在列表处于无法添加的状态
![P4SL@_3ILJ6ME _IJ@KYZML](https://user-images.githubusercontent.com/64689710/82488513-98977200-9b12-11ea-8d7b-90b6c94caa4a.png)

**Comment by CHKZL** [comment]
emmmm，你加DDTV群(307156949)没有，我单独给你出一版手动加载版的客户端，手动把网页内容复制过去然后自动加载

**Comment by CHKZL** [comment]
写了一个多重数据源加载和本地文件备用的特殊客户端= =

**Comment by CHKZL** [comment]
问题已解决
