### ISSUE TITLE
不再获取牌子信息了吗？

### ISSUE THREAD

**Issue by cyb233** [CHKZL/DDTV#203]
https://github.com/CHKZL/DDTV/blob/23db8cd676c28da974037448a9ae2812e5aac7b0/DDTV_Core/SystemAssembly/ConfigModule/BilibiliUserConfig.cs#L281

这导致更换牌子时的检查无法获取牌子信息

https://github.com/CHKZL/DDTV/blob/23db8cd676c28da974037448a9ae2812e5aac7b0/DDTV_Core/SystemAssembly/BilibiliModule/API/UserInfo.cs#L342-L366
```csharp
344     foreach (var item in BilibiliUserConfig.FansMedal) 
```

**Comment by CHKZL** [comment]
我检查了git记录，这段代码确实是被错误的注释了，通过查看git记录发现是在注释调试代码： 

https://github.com/CHKZL/DDTV/blob/23db8cd676c28da974037448a9ae2812e5aac7b0/DDTV_Core/SystemAssembly/ConfigModule/BilibiliUserConfig.cs#L282

的时候，错误的把

https://github.com/CHKZL/DDTV/blob/23db8cd676c28da974037448a9ae2812e5aac7b0/DDTV_Core/SystemAssembly/ConfigModule/BilibiliUserConfig.cs#L281

也给一并注释了，该错误将在之后的版本推送中修复

**Comment by cyb233** [comment]
顺便我想问下，有没有研究过直播间粉丝牌的经验获取是和什么有关的？使用DDTV打开直播间时，是否是保持着进入直播间状态？能否获取粉丝牌时长经验？
