### ISSUE TITLE
会增加音量单独调节和置顶窗口吗？

### ISSUE THREAD

**Issue by xuqingxin001** [CHKZL/DDTV#209]
现在的版本只能多窗口一起调节音量 而且处理其他事情就会盖住播放窗口

**Comment by CHKZL** [comment]
> 现在的版本只能多窗口一起调节音量 而且处理其他事情就会盖住播放窗口

> 现在的版本只能多窗口一起调节音量 而且处理其他事情就会盖住播放窗口

音量调节已经修复，之前会一起调节是由于BUG。窗口置顶在接下来的版本中很快就会增加

**Comment by CHKZL** [comment]
在 [a205449e6e7cf4a2d8c04976c05d66b472342754 ](https://github.com/CHKZL/DDTV/commit/a205449e6e7cf4a2d8c04976c05d66b472342754)中增加了窗口置顶功能，并且已于5.1.42版本中发布，直接在软件内升级或下载最新的releases包即可使用

**Comment by xuqingxin001** [comment]
> 在 [a205449e6e7cf4a2d8c04976c05d66b472342754 ](https://github.com/CHKZL/DDTV/commit/a205449e6e7cf4a2d8c04976c05d66b472342754)中增加了窗口置顶功能，并且已于5.1.42版本中发布，直接在软件内升级或下载最新的releases包即可使用

改成vlc模式窗口后 时不时播放会卡住是什么原因 只能靠刷新重新加载

**Comment by CHKZL** [comment]
> > 在 [a205449e6e7cf4a2d8c04976c05d66b472342754 ](https://github.com/CHKZL/DDTV/commit/a205449e6e7cf4a2d8c04976c05d66b472342754)中增加了窗口置顶功能，并且已于5.1.42版本中发布，直接在软件内升级或下载最新的releases包即可使用
> 
> 改成vlc模式窗口后 时不时播放会卡住是什么原因 只能靠刷新重新加载

请问这个卡住具体是指的什么症状？是停止播放、频繁缓冲、窗口无响应，还是说其他的症状？

**Comment by xuqingxin001** [comment]
> > > 在 [a205449e6e7cf4a2d8c04976c05d66b472342754 ](https://github.com/CHKZL/DDTV/commit/a205449e6e7cf4a2d8c04976c05d66b472342754)中增加了窗口置顶功能，并且已于5.1.42版本中发布，直接在软件内升级或下载最新的releases包即可使用
> > 
> > 
> > 改成vlc模式窗口后 时不时播放会卡住是什么原因 只能靠刷新重新加载
> 
> 请问这个卡住具体是指的什么症状？是停止播放、频繁缓冲、窗口无响应，还是说其他的症状？

停止播放

**Comment by CHKZL** [comment]
> 停止播放 

停止播放可能是缓冲速度没跟上播放速度，导致播放到文件尾了。这种情况下一般是网络问题导致的。

如果确定不是网络速度和延迟的问题，或经常出现这个问题，可以加开发聊天群沟通，通过这交流太累了。Q群：338182356
