### ISSUE TITLE
窗口大小

### ISSUE THREAD

**Issue by Krystal579** [CHKZL/DDTV#217]
拉动窗口大小时视频播放页面比例不变就会出现白边，希望能像旧版那样固定宽高比拉动窗口
<img width="115" alt="Snipaste_2024-07-13_17-17-01" src="https://github.com/user-attachments/assets/7ab1819c-2f0e-4aa5-9296-1055f4d8ce53">

**Comment by CHKZL** [comment]
> 拉动窗口大小时视频播放页面比例不变就会出现白边，希望能像旧版那样固定宽高比拉动窗口 

这是由于现在开播不一定是16:9，有竖屏以及其他分辨率的直播（现在甚至可以推1:1分辨率的直播），为了兼容其他分辨率，所以现在不锁窗口比例了
