### ISSUE TITLE
关于录播的大小以及清晰度问题

### ISSUE THREAD

**Issue by yuna4747** [CHKZL/DDTV#218]
录制的时候能选择清晰度之类的选项吗，比如说录制时优先原画之类的选项

**Comment by CHKZL** [comment]
> 录制的时候能选择清晰度之类的选项吗，比如说录制时优先原画之类的选项

![image](https://github.com/user-attachments/assets/4db28db6-9c79-4d18-9145-befd5d5c6eca)

**Comment by yuna4747** [comment]
> > 录制的时候能选择清晰度之类的选项吗，比如说录制时优先原画之类的选项
> 
> ![image](https://private-user-images.githubusercontent.com/20613600/352711593-4db28db6-9c79-4d18-9145-befd5d5c6eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Mjk2NzYsIm5iZiI6MTcyMjQyOTM3NiwicGF0aCI6Ii8yMDYxMzYwMC8zNTI3MTE1OTMtNGRiMjhkYjYtOWM3OS00ZDE4LTkxNDUtYmVmZDVkNWM2ZWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNzU5MzVmMTI4Y2U0Y2NmZjk3ZjAzYjI1NWM3MmYyNDA5N2FhZjMwZDA3OGE0ZTkzM2I0Y2NlNDk1MmQ4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v2IIRjg06UDR24pB3xbdDHMY-xYQ8kg5tQq16Ed-_oM)

![image](https://github.com/user-attachments/assets/40625f4c-b712-43dc-bf55-8509e6eaccce)
是版本问题吗，我这边并没有这些选项

**Comment by yuna4747** [comment]
然后我还想问一下就是关于首页这边部分的通信协议用的是ipv6，已经平时日常会24h开着梯子，主界面上都显示的异常会影响正常的录播功能吗
![image](https://github.com/user-attachments/assets/ce05d15b-4d2d-4ed4-becd-731781721334)

**Comment by CHKZL** [comment]
在最新的版本中提供了清晰度修改的功能，以及首页的“异常”修改为了其他正常描述以免误解
