### ISSUE TITLE
同时播放多个直播间时有时无法独立调节音量

### ISSUE THREAD

**Issue by kirayomato** [CHKZL/DDTV#219]
有时候会出现调整一个直播间的音量时其他直播间音量也被联动更改的情况，似乎是卡了刷新以后容易出现这个问题

**Comment by CHKZL** [comment]
> 有时候会出现调整一个直播间的音量时其他直播间音量也被联动更改的情况，似乎是卡了刷新以后容易出现这个问题

这个版本应该在5.1.60版本之后就已经修复了，你现在用的是什么版本？如果是最新版本，能描述一下是怎么复现么？
