### ISSUE TITLE
[Bug]: 建議添加錄製時避免電腦進入睡眠的功能

### ISSUE THREAD

**Issue by XPRAMT** [CHKZL/DDTV#226]
### 咋了？

錄製時電腦進入睡眠狀態，導致錄製中斷

### 怎么复现？

電腦設置睡眠時間並錄製

### 分支

main (DDTV5)

### 你运行 DDTV 的电脑系统是什么？

Windows 11

### 哪个版本的 DDTV?

DDTV5_Destkop

### 你 100% 确定你在使用最新的开发板吗？在打勾前请运行一次检查更新。

- [X] 是的，我 100% 确定。

### 相关日志

![9118ca111b32507c3994ae948a38db75](https://github.com/user-attachments/assets/3d14b949-6f70-4fce-9574-cd8e8610a2d0)

**Comment by CHKZL** [comment]
![96ff2038359826f919f322c59c4e04af](https://github.com/user-attachments/assets/4536f919-4031-4957-a3c3-b54b731cdad1)

已在 a9a78a540c273e94b3e8a65797e8fdb491535edd 中增加了阻止系统休眠的配置功能，并编译推送到开发版本：Dev-5.1.89更新中，可以在设置中打开“开发版本”开关后进行手动触发更新到最新版本使用该用能。

**Comment by XPRAMT** [comment]
感謝大佬！
