### ISSUE TITLE
[Feature Request]: 增加录制历史查看

### ISSUE THREAD

**Issue by kawaii0683** [CHKZL/DDTV#228]
### 你希望开发者添加什么功能？

以前的版本 有个录制完成的记录  就是记录了我今天都录过谁
现在的版本没有这个功能  每次我都要进保存目录 挨个找 今天录过谁
希望能够改进 谢谢大佬

### 什么使用场景？

以前的版本 有个录制完成的记录  就是记录了我今天都录过谁
现在的版本没有这个功能  每次我都要进保存目录 挨个找 今天录过谁
希望能够改进 谢谢大佬

### 相关信息

以前的版本 有个录制完成的记录  就是记录了我今天都录过谁
现在的版本没有这个功能  每次我都要进保存目录 挨个找 今天录过谁
希望能够改进 谢谢大佬

**Comment by CHKZL** [comment]
![image](https://github.com/user-attachments/assets/aace9bdc-e5f7-4a33-a01b-f03eac2a6ff0)

已在 c846d63d9d833a22263e37fdf74bd14a54b263e8 中增加了本次启动的录制历史记录和查看功能，并编译推送到开发版本：Dev-5.1.91，可以在releases中下载最新的Dev版本，或者在设置中打开“开发版本”开关后进行手动触发更新到最新版本使用该用能。
