### ISSUE TITLE
[Feature Request]: 窗口标签能不能和旧版一样改成直播间标题 现在的用obs采集的时候不太好区分ww

### ISSUE THREAD

**Issue by Hello-Moeka** [CHKZL/DDTV#232]
### 你希望开发者添加什么功能？

窗口标签能不能和旧版一样改成直播间标题 现在的用obs采集的时候不太好区分ww

### 什么使用场景？

用obs采集的时候方便区分

**Comment by CHKZL** [comment]
在 e9eabd5f47610edf3afcbcc5ae65cadd0c56b093中添加了相关功能：
- 升级UI依赖
- 升级VLC依赖
- 给播放窗口增加窗口标题信息以提高辨识度
![image](https://github.com/user-attachments/assets/372f8f06-7709-407e-b43a-d9bdee295ff1)


----  

已推送到开发版本，可以到 https://github.com/CHKZL/DDTV/releases/tag/dev5.1.102 下载，或在Desktop中打开开发版更新推送后更新到最新版本体验使用
