### ISSUE TITLE
[Bug]: 录播没法停止（？）

### ISSUE THREAD

**Issue by Moment0901** [CHKZL/DDTV#235]
### 咋了？

直播完之后还显示在录播，点取消也不行，重开软件之后也没录播，估计是根本没录
房间页面忘了截图了，就是录制是粉色的，弹幕和提醒是蓝色的，显示录制中

### 怎么复现？

![微信截图_20240917010045](https://github.com/user-attachments/assets/c24c08bf-1769-4d09-9aa3-d8d99d37001f)
![微信截图_20240917010105](https://github.com/user-attachments/assets/00cdb761-5096-44ad-966e-6a45f64865b9)
![微信截图_20240917010122](https://github.com/user-attachments/assets/551d4c8e-d9d1-4336-8b3b-11322e73d2a9)
![微信截图_20240917010200](https://github.com/user-attachments/assets/37292dcb-d98e-4fe6-a0e9-c3305842fd9e)
![微信截图_20240917010211](https://github.com/user-attachments/assets/25e915cc-a419-41b8-9253-8addd7a4adc7)

### 分支

main (DDTV5)

### 你运行 DDTV 的电脑系统是什么？

Windows 11

### 哪个版本的 DDTV?

DDTV5_Destkop

### 版本号多少？

5.1.95.1555

### 你 100% 确定你在使用最新的开发版吗？在打勾前请确保打开[接受开发版本]的开关，再运行一次检查更新。

- [ ] 是的，我 100% 确定。

**Comment by CHKZL** [comment]
从提供的日志截图来看，是正常工作的，没有什么问题。
另外重启过后本来就不会显示历史记录，历史记录只针对本次启动中录制的任务生效，关闭后清空记录，如果需要查看历史文件请到录制文件夹中查看。

录制中提示等待过久的问题在某个新版本中有过优化逻辑，请先更新到最新版本后再确定问题提交issues
https://github.com/CHKZL/DDTV/commit/2c6c8a6071d609f82b3049558f1672c0821ba8fe

**Comment by Moment0901** [comment]
但是我录播只录到9点18下播那次，之后的完全没有
![图片](https://github.com/user-attachments/assets/88cdaf0c-0e57-46df-807e-1acbc452543c)
正常来说下播之后不到1分钟录播就保存好了
![图片](https://github.com/user-attachments/assets/1572ba49-6659-40da-b0a2-1e9b3484f536)
主播在9点58分重新直播，但是软件显示跳过本次任务
![图片](https://github.com/user-attachments/assets/49c9e9a1-0e90-4997-afa1-a66caec27d41)
之后的直播直到我手动关掉录播之前都没有要保存的意思，而且还关不掉
这时候去看录播文件夹，是没有第二次直播的录像的
结果就是我只能关掉软件重新打开

**Comment by CHKZL** [comment]
请升级到最新版本后再试，在issues创建的时候，已经有一个新版本对相关问题进行了fix

**Comment by Moment0901** [comment]
好的，我先试试
