### ISSUE TITLE
[Feature Request]: 第一次用，提几个不影响使用的小建议

### ISSUE THREAD

**Issue by GongT** [CHKZL/DDTV#236]
### 你希望开发者添加什么功能？

在linux上用的（server）

* 如果配置文件不可写，目前启动过程会直接尬住（好像有死锁），ctrl+c也退不出去
* 希望可以把错误直接输出到stderr上，而不是数据库或者文件
* 希望日志去掉时间戳
* 希望临时文件可以放到`$XDG_RUNTIME_DIR`或`/tmp`
* 希望配置文件位置可以通过环境变量或者命令行自定义
* 允许设置为不用密码打开webui
* 文档中`./bin/Server.dll`似乎需要改成`./bin/Server`
* 根据[这里](https://github.com/actions/upload-artifact#permission-loss)的说明，`chmod +x`实际没有起作用，下载的包里所有文件都没有可执行位

### 什么使用场景？

主要原因是打算在docker中运行，并且通过systemd管理。docker和systemd都有非常完善的日志系统，多一个时间戳反而更乱了，错误输出到数据库或者文件也不方便看。

目前发现 程序根目录中的`Config`和`Temporary` 需要写入权限，`Server`

都是一些无关紧要的东西，主要是给其他linux用户作参考（不折腾用什么linux.jpg

**Comment by GongT** [comment]
还是存在启动过程卡死的情况，之后有空我得调试一下

**Comment by CHKZL** [comment]
仔细看下来， 这里面提到的问题，都是在正常screen环境下不会出现问题的case，如果针对docker，请将相关issues提到[moomiji/docker-ddtv](https://github.com/moomiji/docker-ddtv)项目中方便群友进行整合fix

**Comment by GongT** [comment]
我是打算在docker中运行，实际上还没有

**Comment by CHKZL** [comment]
> 我是打算在docker中运行，实际上还没有

那你可以在上面提到的项目中提issues，我们都在同一个群，如果大家觉得有必要的，我们都会挨着处理

**Comment by GongT** [comment]
好的！
