### ISSUE TITLE
[Feature Request]: 希望docker版能支持UMASK和ipv6访问

### ISSUE THREAD

**Issue by shanyan-wcx** [CHKZL/DDTV#240]
### 你希望开发者添加什么功能？

支持UMASK

### 什么使用场景？

使用SMB来管理NAS上的文件时没有权限。
出门在外用手机远程管理。

**Comment by SeeleVolleri** [comment]
https://github.com/CHKZL/DDTV/blob/master/Doc/docs/install/Docker.md
文中已给出环境变量 `PUID` 与 `PGID`. 将其修改为你希望的值即可。

**Comment by CHKZL** [comment]
楼上已经回答了第一个问题，
第二个问题是否为ipv6访问，完全取决于你的网络环境和系统设置，这个在程序里没控制逻辑
