### ISSUE TITLE
DD@Home 合作申请

### ISSUE THREAD

**Issue by simon300000** [CHKZL/DDTV#3]
你好呀，我是vtbs.moe <https://vtbs.moe/about> 的主要开发者，这个网站有数据观测和直播提醒之类的功能。
前几日bilibili升级了策略，导致我的爬虫出现了问题。为了解决这个问题，我做了一个很简单的分布式的爬虫，这样能在bilibili的vtb/vup越来越多的情况下让爬虫在更大的负担下稳定运行。

爬虫使用WebSocket连接，有一个很简单的协议，可以自行设定爬取频率
<https://github.com/dd-center/Cluster-center>

想请问，DDTV有没有来一起合作的可能呢？

**Comment by CHKZL** [comment]
OK，可以哇，我发送了邮件到您个人页留的邮箱simon3000，请查收。

**Comment by simon300000** [comment]
嗯，我回了邮件，似乎因为网络问题回了2个233
