### ISSUE TITLE
功能建议：在当场直播结束后自动将flv文件转码为MP4

### ISSUE THREAD

**Issue by Xuan0cheng** [CHKZL/DDTV#30]

**Comment by CHKZL** [comment]
实际上在2.0.2.4a版本后就增加了这个功能。。在设置界面有一个录制完成后自动转码的选项。。

**Comment by Xuan0cheng** [comment]
> 实际上在2.0.2.4a版本后就增加了这个功能。。在设置界面有一个录制完成后自动转码的选项。。

抱歉，在DDTV本体有这个功能，但DDTVLiveRec分支我并没有从文档中查找到配置方法。
请问在DDTVLiveRec中有实装这个功能吗？

**Comment by CHKZL** [comment]
噢，LR因为涉及到跨平台的支持，而且对于性能羸弱的arm和单核服务器来说转码会造成CPU满载导致其他录制任务失败，所以没测试过也就没有加入。
我之后的版本里尝试增加这个功能，并且设置开关配置试试
