### ISSUE TITLE
DDTVLiveREC运行报错

### ISSUE THREAD

**Issue by Janet-Baker** [CHKZL/DDTV#31]
最新版。前天还能正常运行，今天就不行了。
> Error:
>   An assembly specified in the application dependencies manifest (DDTVLiveRec.deps.json) was not found:
>     package: 'AWSSDK.Core', version: '3.3.0.0'
>     path: 'AWSSDK.Core.dll'

**Comment by CHKZL** [comment]
是什么平台下运行的？能截一张DDLR的根目录文件列表么?我确认一下这是文件缺失还是依赖错误造成的问题。

**Comment by Janet-Baker** [comment]
DDTVLiveRec_for_linux_x64.rar  Centos 7.6
```
[root@linode ~]# uname -a
Linux linode 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
[root@linode LiveREC]# ls -aln
total 97696
drwxr-xr-x  4 0 0        94 Aug 29 22:28 .
drwxr-xr-x. 6 0 0        92 Aug 26 15:10 ..
-rw-r--r--  1 0 0       392 Aug 26 15:13 BiliUser.ini
-rwxrwxrwx  1 0 0 100030520 May 25 17:08 DDTVLiveRec
drw-r--r--  2 0 0       287 Aug 26 22:38 LOG
-r-xr-xr-x  1 0 0       179 Aug 26 15:16 RoomListConfig.json
drwxr-xr-x  3 0 0        94 Aug 22 20:29 tmp
```

**Comment by Janet-Baker** [comment]
已回滚到2.0.3.1a，可以正常运行，只是会提示更新。
这一版本是更改了什么吗？为什么会出现AWS这种东西

**Comment by CHKZL** [comment]
最新版本不就是2.0.3.3a么....这个版本应该不会提示更新。
AWSSDK.Core是用于websocket连接阿B服务器的时候进行包处理的JsonMapper的依赖，AWSSDK在2.0.2.4a更新的时候就已经加入了，应该也不会是AWSSDK的原因才对。

我本地测试了几次没有办法复现这个错误，猜测是由于系统软件环境导致的文件相对路径错误或者配置错误的问题导致文件缺失。

**Comment by CHKZL** [comment]
重新部署一次最新版本也是这样的错误么？
如果还是这样的错误，请加群307156949，单独联系我(群主)，我编译一份“非单体文件”的版本发给你试一试.

**Comment by Janet-Baker** [comment]
我试过了，改文件夹位置和重新上传文件，都不行。

**Comment by CHKZL** [comment]
那请加群307156949我编译一份“非单体文件”的版本发给你
