### ISSUE TITLE
建议：登录账号者可以通过个人中心来获取开播信息

### ISSUE THREAD

**Issue by darth-zhang** [CHKZL/DDTV#34]
最近发现一个油猴脚本
https://greasyfork.org/zh-CN/scripts/378325-bilibili-b%E7%AB%99%E5%BC%80%E6%92%AD%E6%8F%90%E9%86%92
可以通过 个人中心-我的关注 ( https://link.bilibili.com/p/center/index#/user-center/follow/1 ) 来获取关注人开播状态，并通过浏览器通知推送，这个脚本反应速度很快，开播不到一分钟就有推送，但是浏览器通知没有声音，经常就忽略掉了，而且这个脚本要一直开着一个标签，我就想如果DDTV既然可以选择登录账号，是不是也可以把这里作为获取开播信息的方式？
通过这种方式可以获取全部关注人的开播状态，而且可以直接获取主播B站ID (vtbs有些V的名称是错误的)，并且不会因为访问太频繁被ban IP，我用这个脚本有一个多月了，很安全。

**Comment by CHKZL** [comment]
看了一下这个脚本的代码，DDTV里也使用了类似的操作和相同的接口，但是之前没注意关注关注中心返回的json里有live_status状态。
现在DDTV获取直播状态的操作是通过ws连接获取的，实际延迟约为0.5s*单推列表数量+15s，应该比使用这种轮询API的方法快。
下一个版本我尝试添加上这个功能代替原生API单独查询，但是默认还是以现有。
