### ISSUE TITLE
DDTVLiveRec 重新载入配置文件

### ISSUE THREAD

**Issue by RuioWolf** [CHKZL/DDTV#36]
目前是只有重新打开才可以重载配置文件吗？

如果是的话，是否可以实现不重启重载配置文件，比如访问 `/config` 的时候里面增加一个 reload 按钮？或者访问的时候直接重载一次。

**Comment by CHKZL** [comment]
可以不重启，只是为了保证严谨写了推荐重启，只要在访问配置界面后提示修改后就会生效，不需要从新启动，生效后的录制任务都会使用新的配置方式，但是修改前已经开始录制的任务不受影响还是使用老的配置方式

**Comment by RuioWolf** [comment]
如果是针对房间列表录播状态和新增录播房间的操作也是可以访问 `/config` 进行刷新吗？
