### ISSUE TITLE
下载的弹幕文件无法转化为可内嵌入视频的ass文件

### ISSUE THREAD

**Issue by bioope** [CHKZL/DDTV#37]
首先感谢大佬的DDTV！太强了！终于一个屏幕也能当监控室大爷了！
发现的问题是：下载的弹幕文件无法转化为可内嵌入视频的ass文件。
一般而言，下载哔哩哔哩视频弹幕，可以通过danmaku2ass等转换为ass弹幕文件，方便内嵌。
可是DDTV下载的弹幕文件无法转化。
俺不会编程，也看不懂代码，不知道是不是还有别的方法可以将弹幕内嵌的。请大佬教我！

**Comment by CHKZL** [comment]
这个功能我已经在最新的代码里面修复了，生成了符合规范的xml文件，可以使用danmaku之类的软件转换，下一个版本会更新

**Comment by bioope** [comment]
感谢！！
