### ISSUE TITLE
Win10系统勾选提醒无效

### ISSUE THREAD

**Issue by bioope** [CHKZL/DDTV#38]
Win10系统勾选提醒无效！
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.18363 暂缺 Build 18363
不知道是不是我自己哪里没弄好呜呜呜
勾选了提醒开播 提醒窗口却从没弹出来过

杀毒软件是ESET 还有一个Wise AD clearner 
均没有拦截弹窗或是黑名单的记录

**Comment by CHKZL** [comment]
需要有几点需要注意和确认一下
1.勾选过后需要直播间从“未开播”转变为“正在直播”才会提醒
2.直播间开播过后如果是vtbs([这个网站](https://vtbs.moe/))有记录的直播间，开播后60秒内肯定会提醒，如果是三次元或者vtbs未记录的直播间，需要的时间根据你的列表长度变化(连接频率太快会导致阿B黑名单)，连接的速度大概为10秒一个，如果vtbs未记录的直播间过后，可能会导致启动DDTV后连接初始化时间较长，比如50个直播间就需要50x10 大约500秒
3.如果房间号为3三位数或者更短的短号，这些房间号是会经过二次解析的，不是真实房间号，监控的时候需要填写真实房间号(下一个版本会加入自动转换)

**Comment by bioope** [comment]
谢谢！C佬永远的神
