### ISSUE TITLE
关于直播状态的刷新频率问题的一点小建议

### ISSUE THREAD

**Issue by Ars1239** [CHKZL/DDTV#4]
您好，首先对于您开发了此软件表示由衷的感谢！

虽然很好用，但是我个人认为目前“单推列表”直播状态刷新频率还是有点太快了，而且每次刷新都会导致关注列表顶回首行，对于我（这个臭DD）来说，想选中靠后的直播间极其困难。

因此，我希望您能够费神改善此问题，最好能将“单推列表”界面改为每次刷新状态不回顶到首行，或者是允许用户自主设置刷新频率（当然，下限0.5秒还是少不了的），感谢！

**Comment by CHKZL** [comment]
OK~
这个问题已经记录，并且解决，将在下次更新的时候一起推送
在exe.config配置文件里增加了“LiveListTime”关键值，启动的时候将读取这个值当作刷新时间，单位为秒
