### ISSUE TITLE
打开播放窗口 主播结束直播后关闭窗口导致DDTV闪退

### ISSUE THREAD

**Issue by RuioWolf** [CHKZL/DDTV#41]
2.0.4.3c 目前反复出现

**Comment by CHKZL** [comment]
> 2.0.4.3c 目前反复出现

有特定的触发条件或者规律吗。
或者有什么感觉不对的地方？

麻烦告知一下系统环境，比如系统版本，内存大小，CPU型号之类的，方便排查问题

**Comment by LeoChen98** [comment]
> > 2.0.4.3c 目前反复出现
> 
> 有特定的触发条件或者规律吗。
> 或者有什么感觉不对的地方？
> 
> 麻烦告知一下系统环境，比如系统版本，内存大小，CPU型号之类的，方便排查问题

根据经验，目测这种情况应该是出现在主播下播后，room_init或相关接口格式变动，导致json解码出现null并将null传入了不接受null指的函数或者表达式中导致的，建议检查退出逻辑。

**Comment by CHKZL** [comment]
进过排查，没有复现这个现象，只能通过脑内模拟的debug(
现在有怀疑对象：
1.DDTV所在的路径比较特殊，关闭窗口的时候会尝试删除缓存文件，如果没有权限被阻止了可能会造成异常
2.问题出在vlc本身

**Comment by CHKZL** [comment]
根据最近一个月的测试和用户反馈来看，这个问题应该是解决了，这段时间里面重构了文件删除的委托和vlc的操作包装
