### ISSUE TITLE
无法批量修改、修改删除按钮、非vtb无监控、播放窗口建议

### ISSUE THREAD

**Issue by Andy8r0X** [CHKZL/DDTV#42]
版本: DDTV-2.0.4.3c
系统: Windows 7
说明: 
(1) 录制和提醒状态，只能一个个修改或开启RoomListConfig.json修改，无法使用按钮批量修改。
(2) #15 图中有修改和删除钮，而新版没有此功能
![2020-11-21_024211](https://user-images.githubusercontent.com/2507836/99838134-9ab2ba00-2ba3-11eb-8f39-575e3bfaae77.png)
(3) 非vtb无法监控开播状态
(4) 播放窗口若能使用Esc键关闭会更好

**Comment by CHKZL** [comment]
新版本已经单独设计了一个可以方便修改信息的工具，和可以监控非VTB直播间，在这几天就会更新

**Comment by CHKZL** [comment]
在[9f609fe]更新中已经解决了这个问题，在DDTV2.0.4.5b更新中已经附带了修改工具
