### ISSUE TITLE
这个软件的弹幕不能用弹弹play之类和视频一起播放

### ISSUE THREAD

**Issue by gandayfreedm468** [CHKZL/DDTV#43]
电脑系统版本：windows10 64位
使用的DDTV2版本：DDTV-2.0.4.3c
一直喜欢使用的弹幕视频观看软件：
弹弹play（http://www.dandanplay.com/）
windows micrsoft商店下载的bilibili客户端UVP

RT，能否输出录制弹幕是普通B站弹幕风格的xml格式弹幕？以便我用弹弹play之类可以回顾视频当时的弹幕？
只能打开视频不能一起播放弹幕好无聊呀！而且有时候我D的V有同传的。需要弹幕同传帮忙理解V说了什么

虽然视频里面左侧有竖排弹幕栏，但是刷的太快不好留意到同传写的翻译。所以需要个B站那种能飘动的弹幕来播放
不知道能否可以实现？

**Comment by CHKZL** [comment]
在[9f609fe]更新中已经解决了这个问题，现在DDTV2.0.4.5b默认输出的是符合格式的xml文件
