### ISSUE TITLE
docker基本命令及制作docker镜像

### ISSUE THREAD

**Issue by zzcabc** [CHKZL/DDTV#46]
大佬，可否将DDTVLiveRec传入json数据，指定下载路径，另外可否编译成docker版

**Comment by CHKZL** [comment]
如果是需要外置硬盘或者更换硬盘，可以直接挂载设备到./tmp目录，下一个版本我将尝试增加指定下载路径的配置文件
docker版本我需要试一下才知道，没怎么用过docker

**Comment by zzcabc** [comment]
Dockerfile文件 
```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0.1-alpine3.14
RUN apk add -U --no-cache tzdata ffmpeg wget unzip && \
    apk add libgdiplus --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    wget -O DDTV-info https://api.github.com/repos/CHKZL/DDTV/releases/latest && \
    DDTVWEBSERVER_RELEASE=$(cat DDTV-info | awk '/tag_name/{print $5;exit}' FS='[r"]') && \
    wget https://github.com/CHKZL/DDTV/releases/latest/download/DDTV_WEB_Server.zip && \
    unzip DDTV_WEB_Server.zip -d DDTV_WEB_Server && \
    mv DDTV_WEB_Server/DDTV_WEB_Server/ DDTV && \
    cd DDTV && \
    wget https://raw.githubusercontent.com/zzcabc/Docker_Buildx_DDTV/master/start.sh && \
    chmod +x start.sh && \
    rm -rf DDTV-info DDTV_WEB_Server.zip DDTV_WEB_Server && \
    apk del tzdata unzip && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache && \
    rm -rf /tmp/*
EXPOSE 11419
WORKDIR /DDTV
ENTRYPOINT ["./start.sh"]
```
退出编辑

`docker build -t 镜像名称 . ` (制作docker镜像，镜像名称后面有个点)

就打包好镜像了

启动镜像
```sh
docker run -d \
    --name ddtv \
    -p 本地端口:11419 \
    -v 本地路径:RoomListConfig.json	\  
    -v 本地路径:DDTV_Config.ini \
    -v 本地路径:BiliUser.ini \
    镜像名称
```

这是我自己项目试验的docker命令，我希望也能为大佬项目共享一点微薄之力

**Comment by zzcabc** [comment]
在启动是还要加一条
-v /usr/local/DDTVLiveRec/TEM:/TEM            这里可以将录制的文件保存到DDTVLiveRec的TEM文件夹下

**Comment by zzcabc** [comment]
RUN yum install dotnet-runtime-5.0  (在制作镜像加入这条，应该可以直接容器内安装.NET5)

**Comment by CHKZL** [comment]
我在和之前把DDTV部署在docker里面的一个人联系，我先问问了再看，开发环境是vs2019+win10

**Comment by zzcabc** [comment]
我推荐是用Linux系统，另外你的开发环境不是问题，你已经做出来并且可以在Linux系统上运行，docker仅仅是个容器，只要容器或宿主机有.NET5的运行时环境，就可以跑起来

**Comment by zzcabc** [comment]
关于实现问题，我会在周六的时候用2.0.4.5b的版本进行实验，这一切均会在centos7系统上运行，有成果我在发issue

**Comment by CHKZL** [comment]
好

**Comment by zzcabc** [comment]
大佬，经在centos7系统上测试2.0.4.5b下是可以正常运行的，解压文件和Dockerfile均在/usr/local/dd目录下
Dockerfile文件
```
FROM mcr.microsoft.com/dotnet/runtime:5.0
MAINTAINER david "****@qq.com"
ADD ./record /DDTVLiveRec
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
WORKDIR /DDTVLiveRec
EXPOSE 11419
ENTRYPOINT ["./DDTVLiveRec"]
```

打包docker命令
`docker build -t ddtv_live_rec:2.0.4.5b .`

`docker run -d -p 11419:11419 -v /usr/local/dd/config/BiliUser.ini:/DDTVLiveRec/BiliUser.ini -v /usr/local/dd/config/RoomListConfig.json:/DDTVLiveRec/RoomListConfig.json -v /usr/local/dd/config/tmp:/DDTVLiveRec/tmp --name record record:1`

已经处于可用状态中

由于2.0.4.5C版本无Linux可执行程序，无法进行测试

**Comment by zzcabc** [comment]
### 我擅自将docker镜像传到了阿里云上，目前仅制作了Linux x64位镜像
以下是运行命令，大佬随意
```
docker run -d \
-- restart always \
-p 11419:11419 \
-v /usr/local/ddtv/config/BiliUser.ini:/DDTVLiveRec/BiliUser.ini \
-v /usr/local/ddtv/config/RoomListConfig.json:/DDTVLiveRec/RoomListConfig.json \
-v /usr/local/ddtv/config/tmp:/DDTVLiveRec/tmp \
--name ddtv \
registry.cn-hangzhou.aliyuncs.com/zzcabc/ddtv_live_rec:2.0.4.5b
```

### 代码解读：
**ddtv 为容器名称，可以随意更改**
跟随dockers服务启动
`-- restart always`
将容器内部的11419端口映射到宿主机的2233端口
`-p 2233:11419`
将此目录下的BiliUser.ini文件映射到容器内部，：后面不可更改
`-v /usr/local/ddtv/config/BiliUser.ini:/DDTVLiveRec/BiliUser.ini`
将此目录下的RoomListConfig.json文件映射到容器内部，：后面不可更改
`-v /usr/local/ddtv/config/RoomListConfig.json:/DDTVLiveRec/RoomListConfig.json`
将此目录下的tmp文件夹映射到容器内部，**：**后面不可更改， **：**前面为录制的存放位置
-v /usr/local/ddtv/config/tmp:/DDTVLiveRec/tmp
将容器命名为ddtv
`--name ddtv`
容器名称
`registry.cn-hangzhou.aliyuncs.com/zzcabc/ddtv_live_rec:2.0.4.5b`

### docker其他命令
启动docker服务   `systemctl start docker`
停止docker服务   `systemctl stop docker`
重启docker服务   `systemctl restart docker`

### 容器操作
进入容器   `docker exec -it ddtv bash`   输入  `exit`   退出
看启动日志   `docker logs -f ddtv`  输入  `CTRL+C` 退出
重启容器   `docker restart ddtv`
停止容器   `docker stop ddtv`
启动容器   `docker start ddtv`
删除容器 (需在容器停止状态)  `docker rm ddtv`
删除镜像  `docker rmi registry.cn-hangzhou.aliyuncs.com/zzcabc/ddtv_live_rec:2.0.4.5b`

**Comment by CHKZL** [comment]
我这对于部署docker有两个疑问
1.DDTVLiveRec没有任何第三方的依赖，只有基本的.NET5依赖。
2.使用docker还需要环境安装docker

使用docker方式发布有什么必要或者优势么= =

**Comment by zzcabc** [comment]
对于openwrt的软路由来说docker环境是装好或可以安装，他们这群人可以使用，对于群晖docker也是可以安装，第二点就是假设机器因某些程序占用了11419端口docker可以改端口，另外你目前没有更改录制保存位置docker也可以，第三点是升级问题，你也说过要备份文件，docker是宿主机和容器分离，我指定好两文件位置就可以直接映射到容器内部，省了一下备份的操作，但是，docker确实很大，光docker-ce就400M+，这是唯一不足的

**Comment by uchuhimo** [comment]
@CHKZL 我提交了一个PR用于添加Docker支持：https://github.com/CHKZL/DDTV2/pull/59

**Comment by zzcabc** [comment]
看到大佬支持docker，这个issue也差不多没用了，先开着吧，留着之后人使用docker可以看一下

**Comment by zzcabc** [comment]
arm64 镜像https://hub.docker.com/r/zzcabc/ddtv 手动在树莓派4b打包

**Comment by moomiji** [comment]
将**发行版打包**成Docker**多架构**镜像：详见我的 [dockerhub](https://hub.docker.com/r/moomiji/ddtv) 或 [ghcr.io]( https://ghcr.io/moomiji/ddtv)

**Comment by uchuhimo** [comment]
我构建的DDTVLiveRec镜像：https://hub.docker.com/r/uchuhimo/ddtv_live_rec
- 包括x64和arm64两种架构
- 使用Github Actions自动构建
- latest从master分支构建，一般会在官方release时更新（不定期）
- dev从dev分支构建，包含了一些没有合并进上游的更改，我自己使用的是这个分支（慎用）
