### ISSUE TITLE
名称一致性

### ISSUE THREAD

**Issue by RadishKin** [CHKZL/DDTV#48]
录制输出的弹幕和礼物文件名能否修改为与视频文件名一致，现在后面有个flv，播放器软件无法自动匹配

**Comment by CHKZL** [comment]
文件名统一问题在[bfd3f643]中修复了

**Comment by link-fgfgui** [comment]
Same Problem
![{CD0FEA00-004C-4D86-9A9C-E117E87A0C95}](https://github.com/user-attachments/assets/f7c9b049-1b42-4f50-acbc-d9f17d787877)
文件名不同的话alist无法识别到有弹幕文件,进而无法播放弹幕
log:
[DDTV_Server-20241210033912.log](https://github.com/user-attachments/files/18067237/DDTV_Server-20241210033912.log)
