### ISSUE TITLE
反馈一下最近发现的疑似bug现象，以及特性建议

### ISSUE THREAD

**Issue by SupppRabit** [CHKZL/DDTV#5]
1. 添加/修改房间时，被其余房间的提醒消息轰炸
2. 删除房间操作无效（似乎跟1.0版本一样的问题）
3. 某一房间的监控开启时，一旦下播，整个程序就自动关闭（这个问题似乎不能经常复现）
4. 监控窗口的设置栏的文本和按钮在窗口较小时重叠

建议：弹幕和字幕显示有些不友好，可以按照窗口调节字体大小，以及添加字体描边来便于阅读

**Comment by CHKZL** [comment]
上面所有的问题应该在当前版本已经修复了
