### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by jingyuexing** [CHKZL/DDTV#50]
https://github.com/CHKZL/DDTV2/blob/4a01074f8d602c2c047767928a1b70fb9607dfeb/PlayW/MainWindow.xaml.cs#L76
这这这,我要到知乎回答[这个问题](https://www.zhihu.com/question/265453795/answer/1611960218)

**Comment by CHKZL** [comment]
推荐看看其他的类里面，有更诡异的代码.jpg，非程序专业出身，是这样的，天马行空“俺寻思”写法
