### ISSUE TITLE
希望能添加xml弹幕文件断流后续传的功能

### ISSUE THREAD

**Issue by bioope** [CHKZL/DDTV#51]
希望大佬能添加xml弹幕文件断流后能续传的功能

**Comment by CHKZL** [comment]
断流续传功在之前的版本中已经添加了，但是仅限于单独录制\观看一个直播间的情况，如果房间数增加就可能断流。
断流是因为最近阿B修改了wss连接的限制，在当前版本中，wss监听+弹幕显示+弹幕录制 加起来超过4个实例就会开始随机断开，这是由于阿B的限制造成的，暂时无法修复
