### ISSUE TITLE
希望在下载队列界面中增加一个手动结束的功能

### ISSUE THREAD

**Issue by aoisummer** [CHKZL/DDTV#53]
有时候播主一直不下播那我不得不等到他下播了才能结束这次录制就很不科学，希望增加个能手动结束的功能。当前直接点取消的话，flv 文件好像直接就被破坏了连索引都没有

**Comment by CHKZL** [comment]
因为下载任务是一个WebClient的异步操作，在windows下这个操作在文件下载完成前，文件流并没有写入对应的路径，如果手动取消了，系统委托会清空已经下载的缓存部分，任何下载事件都是以“文件下载完成才是正常情况”的前提下进行操作的，这个问题暂时无解。
