### ISSUE TITLE
转码后自动删除源文件

### ISSUE THREAD

**Issue by uchuhimo** [CHKZL/DDTV#54]
开启转码功能后，flv和mp4文件并存，消耗了双倍的存储空间，希望能够提供转码成功之后自动删除flv文件的功能，节省存储空间。

**Comment by CHKZL** [comment]
转码功能可能会因为主播的停播机制不同，造成文件头或者文件尾损坏造成合并错误或者合并失败。为了保证数据的完整性，所以专门保留的flv文件

**Comment by uchuhimo** [comment]
如果合并错误或者合并失败，ffmpeg是否会返回非0的exit code？
如果ffmpeg在转码出错的情况下会返回非0的exit code，那么可以在转码结束的时候通过判断exit code来确定是否删除flv文件：
```csharp
private static void Process_Exited(object sender, EventArgs e)
{
    Process P = (Process)sender;
    InfoLog.InfoPrintf("转码任务完成:"+P.StartInfo.Arguments, InfoLog.InfoClass.下载必要提示);
    if (P.ExitCode == 0)
    {
        // 删除flv文件
    }
}
```

**Comment by CHKZL** [comment]
录制结束后合并转码操作前期全是纯文件流操作，并没有使用到ffmpeg，只有合并完成后会使用ffmpeg，保留flv是为了防止奇葩flv合并失败导致文件链丢失

**Comment by uchuhimo** [comment]
@CHKZL 我阅读了相关代码，现在的逻辑会在两个地方进行转码：

1. 如果不需要合并文件，直接转码；
2. 如果需要合并文件，每两个文件合并后进行转码。

如果在转码成功后删除源文件，那么：

1. 在第一种情况下不会有问题；
2. 在第二种情况下，如果发生N个文件合并且N>2，第一次合并发生后合并的flv文件会被删除，导致后续合并失败。

为了防止第二种情况下的错误，可以把第二种情况的转码逻辑修改为：

- 如果需要合并文件，在所有文件合并完成后再进行转码。如果只有部分文件合并成功，那么只有合并成功的文件会进行转码。

这样转码过程就不会影响到合并过程，删除转码成功的源文件不会导致丢失和合并失败。

**Comment by uchuhimo** [comment]
@CHKZL 对应的PR已经提交了：https://github.com/CHKZL/DDTV2/pull/60
