### ISSUE TITLE
自动录屏的bug反馈

### ISSUE THREAD

**Issue by banana-suisei** [CHKZL/DDTV#6]
1、录屏有时候视频时间只有几十秒，但是转成其他格式后视频时间是正常的
2、在转播不稳定时，主播信号断开后恢复，自动录屏停止

**Comment by CHKZL** [comment]
在2.0.2.1b版本之后针对这个问题在设置中增加额“播放缓冲时长”设置选项，修改这个选项的数值可以改善下载和缓冲不断重连和下载失败的问题。
