### ISSUE TITLE
[future]能否添加录制文件达到多少G之后自动切割的功能？

### ISSUE THREAD

**Issue by Zyilin98** [CHKZL/DDTV#64]
因为有些时候的神回很需要快速剪辑 这时候的录播就不能上传到百度云等云盘 而是传到qq群文件 以便快速出片
但是qq群限制最大文件大小 所以能否添加这一功能？ 谢谢！

**Comment by xia0ti** [comment]
同求这个功能，比如b站的上传视频大小有限制，能不能超过4g左右自动分p呢？非常感谢！

**Comment by CHKZL** [comment]
> 同求这个功能，比如b站的上传视频大小有限制，能不能超过4g左右自动分p呢？非常感谢！

当前的一些底层设计实现这个功能对其他功能影响比较大，当前版本下无法实现。
现在计划在.NET6发布后使用.NET6对DDTV进行完全重构，到时候会对这个功能进行实现

**Comment by xia0ti** [comment]
> > 同求这个功能，比如b站的上传视频大小有限制，能不能超过4g左右自动分p呢？非常感谢！
> 
> 当前的一些底层设计实现这个功能对其他功能影响比较大，当前版本下无法实现。
> 现在计划在.NET6发布后使用.NET6对DDTV进行完全重构，到时候会对这个功能进行实现

非常感谢！

**Comment by CHKZL** [comment]
这个问题在1月份的时候发布的DDTV3.x版本中已经实现了，现在就可以直接使用
