### ISSUE TITLE
弹幕框无法输入字母或字符

### ISSUE THREAD

**Issue by kanonmelodis** [CHKZL/DDTV#68]
edit:输入数字或者字母或者字符都会直接失焦只有通过输入法直接输入中文可以

另外能否使用enter发送弹幕 现在只能用鼠标点击按钮体验属实太差

**Comment by CHKZL** [comment]
因为全局老板键和音量键的监听，导致的按键事件冲突，无法输入字符和数字的问题已经解决了
在输入框回车直接发送的功能也实现了
已经提交到https://github.com/CHKZL/DDTV2/commit/7ca63fce77972083d29aff82d6f7e9e23f52bb30

**Comment by CHKZL** [comment]
下次累积更新的时候合并到发布版本中
