### ISSUE TITLE
关于显示同传Man字幕的问题

### ISSUE THREAD

**Issue by whycantiusemyname** [CHKZL/DDTV#7]
这个字幕显示不全
只能看到两句
![image](https://user-images.githubusercontent.com/60563852/76685854-d0d18e80-6651-11ea-80db-3044a15a7aaa.png)

**Comment by CHKZL** [comment]
> 这个字幕显示不全
> 只能看到两句
> ![image](https://user-images.githubusercontent.com/60563852/76685854-d0d18e80-6651-11ea-80db-3044a15a7aaa.png)

就是这样设置的，看最新的两句话，是自动从上往下滚动的
