### ISSUE TITLE
[建议]ddtvliverec下载任务完成后执行自定义指令

### ISSUE THREAD

**Issue by Hato626** [CHKZL/DDTV#70]
如题
一个小建议
下载完成后执行自定义指令
或者下载完成之后提供一个标记，让其他程序（例如网盘cli程序）获取到下载完成的信息来执行指令（例如上传至网盘）

**Comment by CHKZL** [comment]
具体的指令执行类型和方式是啥？

**Comment by Hato626** [comment]
> 具体的指令执行类型和方式是啥？

比如执行 sh批处理脚本
类型是外部指令（可能?不太清楚)

**Comment by CHKZL** [comment]
也就是说
“XXX录播任务完成后执行一个文件”
这样？

**Comment by Hato626** [comment]
对对对

**Comment by Nagico** [comment]
如果是想录制后上传网盘的话，我之前写过一些代码
[https://github.com/NagisaCo/DDTV2/tree/upload](https://github.com/NagisaCo/DDTV2/tree/upload)
不过只支持腾讯云cos和onedriveuploader的上传，如果会c#的话可以自己修改修改
等有时间我把conflict解决后pr过来

<br>

具体的食用方法可以看这个
https://github.com/NagisaCo/DDTV2/tree/upload/DDTVLiveRec#DDTVLiveRec%E4%B8%8A%E4%BC%A0%E6%A8%A1%E5%9D%97%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by Hato626** [comment]
> 如果是想录制后上传网盘的话，我之前写过一些代码
> https://github.com/NagisaCo/DDTV2/tree/upload
> 不过只支持腾讯云cos和onedriveuploader的上传，如果会c#的话可以自己修改修改
> 等有时间我把conflict解决后pr过来
> 
> 
> 具体的食用方法可以看这个
> https://github.com/NagisaCo/DDTV2/tree/upload/DDTVLiveRec#DDTVLiveRec%E4%B8%8A%E4%BC%A0%E6%A8%A1%E5%9D%97%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

有编译好的程序吗 ， 还是需要自己编译

**Comment by Nagico** [comment]
> 有编译好的程序吗 ， 还是需要自己编译

如果是上传至Onedrive或者腾讯云COS，可以直接编译使用，我也编译了个可移植的release  
[https://github.com/NagisaCo/DDTV2/releases/tag/v0.0.1-TestOnly](https://github.com/NagisaCo/DDTV2/releases/tag/v0.0.1-TestOnly)  
需要配置config文件

如果是其他上传目标的话，暂时还没适配

------
目前我已经提交pr了，后续版本的更新可以通过原项目的release里下载

**Comment by Hato626** [comment]
> > 有编译好的程序吗 ， 还是需要自己编译
> 
> 如果是上传至Onedrive或者腾讯云COS，可以直接编译使用，我也编译了个可移植的release  
> [https://github.com/NagisaCo/DDTV2/releases/tag/v0.0.1-TestOnly](https://github.com/NagisaCo/DDTV2/releases/tag/v0.0.1-TestOnly)  
> 需要配置config文件
> 
> 如果是其他上传目标的话，暂时还没适配
> 
> ------
> 目前我已经提交pr了，后续版本的更新可以通过原项目的release里下载

在服务器上挂了5天了，挺好用的,提个建议
能不能把弹幕文件\礼物文件和转码文件也上传

**Comment by Nagico** [comment]
> 在服务器上挂了5天了，挺好用的,提个建议
> 能不能把弹幕文件\礼物文件和转码文件也上传

好的，之后会添加相关功能

**Comment by CHKZL** [comment]
在重构后的3.0版本中大概一年前就增加了任务完成后执行shell命令的功能了= =刚才清issues才发现这个还没关
