### ISSUE TITLE
config相关

### ISSUE THREAD

**Issue by dfmjndm** [CHKZL/DDTV#72]
看了DDTVReciv的config，能不能只下载弹幕文件不下载视频，

还有就是下载视频的清晰度可以调吗有些直播下载下来文件太大了

**Comment by CHKZL** [comment]
如果需要单纯录制弹幕的功能，这个可以单独写一个软件实现，把DDTV的功能屏蔽得只剩下录制弹幕有点困难...耦合度太高了。
视频默认录制是推流大小，大多数直播实际上也都只有原画，没有其他分辨率可选择

**Comment by dfmjndm** [comment]
另外上传百度网盘现在通过bypy可以实现
