### ISSUE TITLE
可以考虑一下添加房间标题吗？

### ISSUE THREAD

**Issue by agustyuzu** [CHKZL/DDTV#74]
![image](https://user-images.githubusercontent.com/37202588/124585201-a8ddee00-de87-11eb-9638-2c2c156e683c.png)
频道房间号的右边可以考虑一下显示直播间标题吗？这个可能比较难写，因为有的主播喜欢播一半改标题。
有房间标题的话，很多场合可以判断应不应该点进去了(

**Comment by CHKZL** [comment]
如果显示标题那按道理这里可能宽度就不够了，得搞个地方插进去，功能本身应该是能加上

**Comment by CHKZL** [comment]
这个问题在几个月前3.0重构的时候就已经解决了
