### ISSUE TITLE
更加合适的文件管理api需求

### ISSUE THREAD

**Issue by hegugu-ng** [CHKZL/DDTV#88]
# 概述
现阶段的`获取文件列表` 的api是将服务端所有文件全部返回，显然非常低效。
所以需要一系列的变更
# 描述
新的api可以通过一个参数 相对于对于 /tmp 的绝对路径 进行处理 返回所给绝对路径下的所有文件与目录信息
新的api可以通过房间号查询到这个房间相对于 /tmp 的绝对路径与内部文件与目录

**Comment by CHKZL** [comment]
可以往 TODO上面加( #81 比如这个issues？)，新功能和更改老功能都放到重构里面一起搞了，现在就把现有的版本弄稳定就行了
