### ISSUE TITLE
添加新单推的时候发现的bug

### ISSUE THREAD

**Issue by whycantiusemyname** [CHKZL/DDTV#9]
![image](https://user-images.githubusercontent.com/60563852/76694498-6f8bd880-66ae-11ea-9e9a-9193b7c536c5.png)
如图
刚添加开播夸进去的时候会显示mea开播，也就是图上的反过来
但是却是夸开播

**Comment by CHKZL** [comment]
这是一个遗留问题，只会在增加列表过后的第一次出现，暂时没有其他影响，后续版本会修复的
